import CreateComponent from "../../CreateComponent.js";

export default ({
     children,
     style,
     styleSheet,
     id,
     alt,
     coords,
     download,
     href,
     hrefLang,
     ping,
     referrerPolicy,
     rel,
     shape,
     target,
     className,
     events,
     renderIf = true,
     hooks,
}) =>
     new CreateComponent({
          tag: "area",
          children,
          inlineStyle: style,
          renderIf,
          props: {
               id,
               alt,
               coords,
               download,
               href,
               href,
               hrefLang,
               ping,
               referrerPolicy,
               rel,
               shape,
               target,
          },
          className: className,
          events: events,
          hooks,
          style: styleSheet,
     });
