import CreateComponent from "../../CreateComponent.js";

export default ({
     style,
     styleSheet,
     id,
     alt,
     crossOrigin,
     decoding,
     height,
     isMap,
     referrerPolicy,
     sizes,
     src,
     srcSet,
     width,
     useMap,
     className,
     events,
     renderIf = true,
     hooks,
}) =>
     new CreateComponent({
          tag: "img",
          inlineStyle: style,
          renderIf,
          props: {
               id,
               alt,
               crossOrigin,
               decoding,
               height,
               isMap,
               referrerPolicy,
               sizes,
               src,
               srcSet,
               width,
               useMap,
          },
          className: className,
          events: events,
          hooks,
          style: styleSheet,
     });
