import CreateComponent from "../../CreateComponent.js";

export default ({
     children,
     style,
     styleSheet,
     id,
     autoplay,
     controls,
     crossOrigin,
     height,
     loop,
     muted,
     playsinline,
     poster,
     preload,
     src,
     width,
     className,
     events,
     renderIf = true,
     hooks,
}) =>
     new CreateComponent({
          children,
          tag: "video",
          inlineStyle: style,
          renderIf,
          props: {
               id,
               autoplay,
               controls,
               crossOrigin,
               height,
               loop,
               muted,
               playsinline,
               poster,
               preload,
               src,
               width,
          },
          className: className,
          events: events,
          hooks,
          style: styleSheet,
     });
