export default function ({
     border = {
          all: null,
          color: null,
          style: null,
          width: null,
          top: null,
          topColor: null,
          topStyle: null,
          topWidth: null,
          bottom: null,
          bottomColor: null,
          bottomStyle: null,
          borderWidth: null,
          left: null,
          leftColor: null,
          leftStyle: null,
          leftWidth: null,
          right: null,
          rightColor: null,
          rightStyle: null,
          rightWidth: null,
     },
     outline,
     borderRadius = {
          all: null,
          topRight: null,
          topLeft: null,
          bottomRight: null,
          bottomLeft: null,
     },
     shape,
     padding = {
          all: null,
          vertical: null,
          horizontal: null,
          left: null,
          right: null,
          top: null,
          bottom: null,
     },
     shadow,
     sizing,
     visiblity,
     height,
     minHeight,
     maxHeight,
     width,
     minWidth,
     maxWidth,
     cursor,
     scrollBehavior,
     transform,
     overflow,
     overflowX,
     overflowY,
     resize,
     growthFactor,
     shrinkFactor,
}) {
     return { ...arguments[0] };
}
