export default ({
     accentColor = "",
     additiveSymbols = "",
     alignContent = "",
     alignItems = "",
     alignSelf = "",
     alignmentBaseline = "",
     all = "",
     animation = "",
     animationDelay = "",
     animationDirection = "",
     animationDuration = "",
     animationFillMode = "",
     animationIterationCount = "",
     animationName = "",
     animationPlayState = "",
     animationTimeline = "",
     animationTimingFunction = "",
     appearance = "",
     ascentOverride = "",
     aspectRatio = "",
     backdropFilter = "",
     backfaceVisibility = "",
     background = "",
     backgroundAttachment = "",
     backgroundBlendMode = "",
     backgroundClip = "",
     backgroundColor = "",
     backgroundImage = "",
     backgroundOrigin = "",
     backgroundPosition = "",
     backgroundPositionX = "",
     backgroundPositionY = "",
     backgroundRepeat = "",
     backgroundRepeatX = "",
     backgroundRepeatY = "",
     backgroundSize = "",
     baselineShift = "",
     blockSize = "",
     border = "",
     borderBlock = "",
     borderBlockColor = "",
     borderBlockEnd = "",
     borderBlockEndColor = "",
     borderBlockEndStyle = "",
     borderBlockEndWidth = "",
     borderBlockStart = "",
     borderBlockStartColor = "",
     borderBlockStartStyle = "",
     borderBlockStartWidth = "",
     borderBlockStyle = "",
     borderBlockWidth = "",
     borderBottom = "",
     borderBottomColor = "",
     borderBottomLeftRadius = "",
     borderBottomRightRadius = "",
     borderBottomStyle = "",
     borderBottomWidth = "",
     borderCollapse = "",
     borderColor = "",
     borderEndEndRadius = "",
     borderEndStartRadius = "",
     borderImage = "",
     borderImageOutset = "",
     borderImageRepeat = "",
     borderImageSlice = "",
     borderImageSource = "",
     borderImageWidth = "",
     borderInline = "",
     borderInlineColor = "",
     borderInlineEnd = "",
     borderInlineEndColor = "",
     borderInlineEndStyle = "",
     borderInlineEndWidth = "",
     borderInlineStart = "",
     borderInlineStartColor = "",
     borderInlineStartStyle = "",
     borderInlineStartWidth = "",
     borderInlineStyle = "",
     borderInlineWidth = "",
     borderLeft = "",
     borderLeftColor = "",
     borderLeftStyle = "",
     borderLeftWidth = "",
     borderRadius = "",
     borderRight = "",
     borderRightColor = "",
     borderRightStyle = "",
     borderRightWidth = "",
     borderSpacing = "",
     borderStartEndRadius = "",
     borderStartStartRadius = "",
     borderStyle = "",
     borderTop = "",
     borderTopColor = "",
     borderTopLeftRadius = "",
     borderTopRightRadius = "",
     borderTopStyle = "",
     borderTopWidth = "",
     borderWidth = "",
     bottom = "",
     boxShadow = "",
     boxSizing = "",
     breakAfter = "",
     breakBefore = "",
     breakInside = "",
     bufferedRendering = "",
     captionSide = "",
     caretColor = "",
     clear = "",
     clip = "",
     clipPath = "",
     clipRule = "",
     color = "",
     colorInterpolation = "",
     colorInterpolationFilters = "",
     colorRendering = "",
     colorScheme = "",
     columnCount = "",
     columnFill = "",
     columnGap = "",
     columnRule = "",
     columnRuleColor = "",
     columnRuleStyle = "",
     columnRuleWidth = "",
     columnSpan = "",
     columnWidth = "",
     columns = "",
     contain = "",
     containIntrinsicSize = "",
     content = "",
     contentVisibility = "",
     counterIncrement = "",
     counterReset = "",
     counterSet = "",
     cursor = "",
     cx = "",
     cy = "",
     d = "",
     descentOverride = "",
     direction = "",
     display = "",
     dominantBaseline = "",
     emptyCells = "",
     end = "",
     fallback = "",
     fill = "",
     fillOpacity = "",
     fillRule = "",
     filter = "",
     flex = "",
     flexBasis = "",
     flexDirection = "",
     flexFlow = "",
     flexGrow = "",
     flexShrink = "",
     flexWrap = "",
     float = "",
     floodColor = "",
     floodOpacity = "",
     font = "",
     fontDisplay = "",
     fontFamily = "",
     fontFeatureSettings = "",
     fontKerning = "",
     fontOpticalSizing = "",
     fontSize = "",
     fontStretch = "",
     fontStyle = "",
     fontVariant = "",
     fontVariantCaps = "",
     fontVariantEastAsian = "",
     fontVariantLigatures = "",
     fontVariantNumeric = "",
     fontVariationSettings = "",
     fontWeight = "",
     forcedColorAdjust = "",
     gap = "",
     grid = "",
     gridArea = "",
     gridAutoColumns = "",
     gridAutoFlow = "",
     gridAutoRows = "",
     gridColumn = "",
     gridColumnEnd = "",
     gridColumnGap = "",
     gridColumnStart = "",
     gridGap = "",
     gridRow = "",
     gridRowEnd = "",
     gridRowGap = "",
     gridRowStart = "",
     gridTemplate = "",
     gridTemplateAreas = "",
     gridTemplateColumns = "",
     gridTemplateRows = "",
     height = "",
     hyphens = "",
     imageOrientation = "",
     imageRendering = "",
     inherits = "",
     initialValue = "",
     inlineSize = "",
     inset = "",
     insetBlock = "",
     insetBlockEnd = "",
     insetBlockStart = "",
     insetInline = "",
     insetInlineEnd = "",
     insetInlineStart = "",
     isolation = "",
     justifyContent = "",
     justifyItems = "",
     justifySelf = "",
     left = "",
     letterSpacing = "",
     lightingColor = "",
     lineBreak = "",
     lineGapOverride = "",
     lineHeight = "",
     lineHeightStep = "",
     listStyle = "",
     listStyleImage = "",
     listStylePosition = "",
     listStyleType = "",
     margin = "",
     marginBlock = "",
     marginBlockEnd = "",
     marginBlockStart = "",
     marginBottom = "",
     marginInline = "",
     marginInlineEnd = "",
     marginInlineStart = "",
     marginLeft = "",
     marginRight = "",
     marginTop = "",
     marker = "",
     markerEnd = "",
     markerMid = "",
     markerStart = "",
     mask = "",
     maskType = "",
     mathDepth = "",
     mathShift = "",
     mathStyle = "",
     maxBlockSize = "",
     maxHeight = "",
     maxInlineSize = "",
     maxWidth = "",
     maxZoom = "",
     minBlockSize = "",
     minHeight = "",
     minInlineSize = "",
     minWidth = "",
     minZoom = "",
     mixBlendMode = "",
     negative = "",
     objectFit = "",
     objectPosition = "",
     offset = "",
     offsetAnchor = "",
     offsetDistance = "",
     offsetPath = "",
     offsetPosition = "",
     offsetRotate = "",
     opacity = "",
     order = "",
     orientation = "",
     orphans = "",
     outline = "",
     outlineColor = "",
     outlineOffset = "",
     outlineStyle = "",
     outlineWidth = "",
     overflow = "",
     overflowAnchor = "",
     overflowClipMargin = "",
     overflowWrap = "",
     overflowX = "",
     overflowY = "",
     overscrollBehavior = "",
     overscrollBehaviorBlock = "",
     overscrollBehaviorInline = "",
     overscrollBehaviorX = "",
     overscrollBehaviorY = "",
     pad = "",
     padding = "",
     paddingBlock = "",
     paddingBlockEnd = "",
     paddingBlockStart = "",
     paddingBottom = "",
     paddingInline = "",
     paddingInlineEnd = "",
     paddingInlineStart = "",
     paddingLeft = "",
     paddingRight = "",
     paddingTop = "",
     page = "",
     pageBreakAfter = "",
     pageBreakBefore = "",
     pageBreakInside = "",
     pageOrientation = "",
     paintOrder = "",
     perspective = "",
     perspectiveOrigin = "",
     placeContent = "",
     placeItems = "",
     placeSelf = "",
     pointerEvents = "",
     position = "",
     prefix = "",
     quotes = "",
     r = "",
     range = "",
     resize = "",
     right = "",
     rotate = "",
     rowGap = "",
     rubyPosition = "",
     rx = "",
     ry = "",
     scale = "",
     scrollBehavior = "",
     scrollMargin = "",
     scrollMarginBlock = "",
     scrollMarginBlockEnd = "",
     scrollMarginBlockStart = "",
     scrollMarginBottom = "",
     scrollMarginInline = "",
     scrollMarginInlineEnd = "",
     scrollMarginInlineStart = "",
     scrollMarginLeft = "",
     scrollMarginRight = "",
     scrollMarginTop = "",
     scrollPadding = "",
     scrollPaddingBlock = "",
     scrollPaddingBlockEnd = "",
     scrollPaddingBlockStart = "",
     scrollPaddingBottom = "",
     scrollPaddingInline = "",
     scrollPaddingInlineEnd = "",
     scrollPaddingInlineStart = "",
     scrollPaddingLeft = "",
     scrollPaddingRight = "",
     scrollPaddingTop = "",
     scrollSnapAlign = "",
     scrollSnapStop = "",
     scrollSnapType = "",
     scrollbarGutter = "",
     shapeImageThreshold = "",
     shapeMargin = "",
     shapeOutside = "",
     shapeRendering = "",
     size = "",
     sizeAdjust = "",
     source = "",
     speak = "",
     speakAs = "",
     src = "",
     start = "",
     stopColor = "",
     stopOpacity = "",
     stroke = "",
     strokeDasharray = "",
     strokeDashoffset = "",
     strokeLinecap = "",
     strokeLinejoin = "",
     strokeMiterlimit = "",
     strokeOpacity = "",
     strokeWidth = "",
     suffix = "",
     symbols = "",
     syntax = "",
     system = "",
     tabSize = "",
     tableLayout = "",
     textAlign = "",
     textAlignLast = "",
     textAnchor = "",
     textCombineUpright = "",
     textDecoration = "",
     textDecorationColor = "",
     textDecorationLine = "",
     textDecorationSkipInk = "",
     textDecorationStyle = "",
     textDecorationThickness = "",
     textIndent = "",
     textJustify = "",
     textOrientation = "",
     textOverflow = "",
     textRendering = "",
     textShadow = "",
     textSizeAdjust = "",
     textTransform = "",
     textUnderlineOffset = "",
     textUnderlinePosition = "",
     timeRange = "",
     top = "",
     touchAction = "",
     transform = "",
     transformBox = "",
     transformOrigin = "",
     transformStyle = "",
     transition = "",
     transitionDelay = "",
     transitionDuration = "",
     transitionProperty = "",
     transitionTimingFunction = "",
     translate = "",
     unicodeBidi = "",
     unicodeRange = "",
     userSelect = "",
     userZoom = "",
     vectorEffect = "",
     verticalAlign = "",
     visibility = "",
     webkitAlignContent = "",
     webkitAlignItems = "",
     webkitAlignSelf = "",
     webkitAnimation = "",
     webkitAnimationDelay = "",
     webkitAnimationDirection = "",
     webkitAnimationDuration = "",
     webkitAnimationFillMode = "",
     webkitAnimationIterationCount = "",
     webkitAnimationName = "",
     webkitAnimationPlayState = "",
     webkitAnimationTimingFunction = "",
     webkitAppRegion = "",
     webkitAppearance = "",
     webkitBackfaceVisibility = "",
     webkitBackgroundClip = "",
     webkitBackgroundOrigin = "",
     webkitBackgroundSize = "",
     webkitBorderAfter = "",
     webkitBorderAfterColor = "",
     webkitBorderAfterStyle = "",
     webkitBorderAfterWidth = "",
     webkitBorderBefore = "",
     webkitBorderBeforeColor = "",
     webkitBorderBeforeStyle = "",
     webkitBorderBeforeWidth = "",
     webkitBorderBottomLeftRadius = "",
     webkitBorderBottomRightRadius = "",
     webkitBorderEnd = "",
     webkitBorderEndColor = "",
     webkitBorderEndStyle = "",
     webkitBorderEndWidth = "",
     webkitBorderHorizontalSpacing = "",
     webkitBorderImage = "",
     webkitBorderRadius = "",
     webkitBorderStart = "",
     webkitBorderStartColor = "",
     webkitBorderStartStyle = "",
     webkitBorderStartWidth = "",
     webkitBorderTopLeftRadius = "",
     webkitBorderTopRightRadius = "",
     webkitBorderVerticalSpacing = "",
     webkitBoxAlign = "",
     webkitBoxDecorationBreak = "",
     webkitBoxDirection = "",
     webkitBoxFlex = "",
     webkitBoxOrdinalGroup = "",
     webkitBoxOrient = "",
     webkitBoxPack = "",
     webkitBoxReflect = "",
     webkitBoxShadow = "",
     webkitBoxSizing = "",
     webkitClipPath = "",
     webkitColumnBreakAfter = "",
     webkitColumnBreakBefore = "",
     webkitColumnBreakInside = "",
     webkitColumnCount = "",
     webkitColumnGap = "",
     webkitColumnRule = "",
     webkitColumnRuleColor = "",
     webkitColumnRuleStyle = "",
     webkitColumnRuleWidth = "",
     webkitColumnSpan = "",
     webkitColumnWidth = "",
     webkitColumns = "",
     webkitFilter = "",
     webkitFlex = "",
     webkitFlexBasis = "",
     webkitFlexDirection = "",
     webkitFlexFlow = "",
     webkitFlexGrow = "",
     webkitFlexShrink = "",
     webkitFlexWrap = "",
     webkitFontFeatureSettings = "",
     webkitFontSmoothing = "",
     webkitHighlight = "",
     webkitHyphenateCharacter = "",
     webkitJustifyContent = "",
     webkitLineBreak = "",
     webkitLineClamp = "",
     webkitLocale = "",
     webkitLogicalHeight = "",
     webkitLogicalWidth = "",
     webkitMarginAfter = "",
     webkitMarginBefore = "",
     webkitMarginEnd = "",
     webkitMarginStart = "",
     webkitMask = "",
     webkitMaskBoxImage = "",
     webkitMaskBoxImageOutset = "",
     webkitMaskBoxImageRepeat = "",
     webkitMaskBoxImageSlice = "",
     webkitMaskBoxImageSource = "",
     webkitMaskBoxImageWidth = "",
     webkitMaskClip = "",
     webkitMaskComposite = "",
     webkitMaskImage = "",
     webkitMaskOrigin = "",
     webkitMaskPosition = "",
     webkitMaskPositionX = "",
     webkitMaskPositionY = "",
     webkitMaskRepeat = "",
     webkitMaskRepeatX = "",
     webkitMaskRepeatY = "",
     webkitMaskSize = "",
     webkitMaxLogicalHeight = "",
     webkitMaxLogicalWidth = "",
     webkitMinLogicalHeight = "",
     webkitMinLogicalWidth = "",
     webkitOpacity = "",
     webkitOrder = "",
     webkitPaddingAfter = "",
     webkitPaddingBefore = "",
     webkitPaddingEnd = "",
     webkitPaddingStart = "",
     webkitPerspective = "",
     webkitPerspectiveOrigin = "",
     webkitPerspectiveOriginX = "",
     webkitPerspectiveOriginY = "",
     webkitPrintColorAdjust = "",
     webkitRtlOrdering = "",
     webkitRubyPosition = "",
     webkitShapeImageThreshold = "",
     webkitShapeMargin = "",
     webkitShapeOutside = "",
     webkitTapHighlightColor = "",
     webkitTextCombine = "",
     webkitTextDecorationsInEffect = "",
     webkitTextEmphasis = "",
     webkitTextEmphasisColor = "",
     webkitTextEmphasisPosition = "",
     webkitTextEmphasisStyle = "",
     webkitTextFillColor = "",
     webkitTextOrientation = "",
     webkitTextSecurity = "",
     webkitTextSizeAdjust = "",
     webkitTextStroke = "",
     webkitTextStrokeColor = "",
     webkitTextStrokeWidth = "",
     webkitTransform = "",
     webkitTransformOrigin = "",
     webkitTransformOriginX = "",
     webkitTransformOriginY = "",
     webkitTransformOriginZ = "",
     webkitTransformStyle = "",
     webkitTransition = "",
     webkitTransitionDelay = "",
     webkitTransitionDuration = "",
     webkitTransitionProperty = "",
     webkitTransitionTimingFunction = "",
     webkitUserDrag = "",
     webkitUserModify = "",
     webkitUserSelect = "",
     webkitWritingMode = "",
     whiteSpace = "",
     widows = "",
     width = "",
     willChange = "",
     wordBreak = "",
     wordSpacing = "",
     wordWrap = "",
     writingMode = "",
     x = "",
     y = "",
     zIndex = "",
     zoom = "",
     cssText = "",
     length = "",
     parentRule = "",
     cssFloat = "",
     getPropertyPriority = "",
     getPropertyValue = "",
     item = "",
     removeProperty = "",
     setProperty = "",
}) => {
     return {
          accentColor: accentColor,
          additiveSymbols: additiveSymbols,
          alignContent: alignContent,
          alignItems: alignItems,
          alignSelf: alignSelf,
          alignmentBaseline: alignmentBaseline,
          all: all,
          animation: animation,
          animationDelay: animationDelay,
          animationDirection: animationDirection,
          animationDuration: animationDuration,
          animationFillMode: animationFillMode,
          animationIterationCount: animationIterationCount,
          animationName: animationName,
          animationPlayState: animationPlayState,
          animationTimeline: animationTimeline,
          animationTimingFunction: animationTimingFunction,
          appearance: appearance,
          ascentOverride: ascentOverride,
          aspectRatio: aspectRatio,
          backdropFilter: backdropFilter,
          backfaceVisibility: backfaceVisibility,
          background: background,
          backgroundAttachment: backgroundAttachment,
          backgroundBlendMode: backgroundBlendMode,
          backgroundClip: backgroundClip,
          backgroundColor: backgroundColor,
          backgroundImage: backgroundImage,
          backgroundOrigin: backgroundOrigin,
          backgroundPosition: backgroundPosition,
          backgroundPositionX: backgroundPositionX,
          backgroundPositionY: backgroundPositionY,
          backgroundRepeat: backgroundRepeat,
          backgroundRepeatX: backgroundRepeatX,
          backgroundRepeatY: backgroundRepeatY,
          backgroundSize: backgroundSize,
          baselineShift: baselineShift,
          blockSize: blockSize,
          border: border,
          borderBlock: borderBlock,
          borderBlockColor: borderBlockColor,
          borderBlockEnd: borderBlockEnd,
          borderBlockEndColor: borderBlockEndColor,
          borderBlockEndStyle: borderBlockEndStyle,
          borderBlockEndWidth: borderBlockEndWidth,
          borderBlockStart: borderBlockStart,
          borderBlockStartColor: borderBlockStartColor,
          borderBlockStartStyle: borderBlockStartStyle,
          borderBlockStartWidth: borderBlockStartWidth,
          borderBlockStyle: borderBlockStyle,
          borderBlockWidth: borderBlockWidth,
          borderBottom: borderBottom,
          borderBottomColor: borderBottomColor,
          borderBottomLeftRadius: borderBottomLeftRadius,
          borderBottomRightRadius: borderBottomRightRadius,
          borderBottomStyle: borderBottomStyle,
          borderBottomWidth: borderBottomWidth,
          borderCollapse: borderCollapse,
          borderColor: borderColor,
          borderEndEndRadius: borderEndEndRadius,
          borderEndStartRadius: borderEndStartRadius,
          borderImage: borderImage,
          borderImageOutset: borderImageOutset,
          borderImageRepeat: borderImageRepeat,
          borderImageSlice: borderImageSlice,
          borderImageSource: borderImageSource,
          borderImageWidth: borderImageWidth,
          borderInline: borderInline,
          borderInlineColor: borderInlineColor,
          borderInlineEnd: borderInlineEnd,
          borderInlineEndColor: borderInlineEndColor,
          borderInlineEndStyle: borderInlineEndStyle,
          borderInlineEndWidth: borderInlineEndWidth,
          borderInlineStart: borderInlineStart,
          borderInlineStartColor: borderInlineStartColor,
          borderInlineStartStyle: borderInlineStartStyle,
          borderInlineStartWidth: borderInlineStartWidth,
          borderInlineStyle: borderInlineStyle,
          borderInlineWidth: borderInlineWidth,
          borderLeft: borderLeft,
          borderLeftColor: borderLeftColor,
          borderLeftStyle: borderLeftStyle,
          borderLeftWidth: borderLeftWidth,
          borderRadius: borderRadius,
          borderRight: borderRight,
          borderRightColor: borderRightColor,
          borderRightStyle: borderRightStyle,
          borderRightWidth: borderRightWidth,
          borderSpacing: borderSpacing,
          borderStartEndRadius: borderStartEndRadius,
          borderStartStartRadius: borderStartStartRadius,
          borderStyle: borderStyle,
          borderTop: borderTop,
          borderTopColor: borderTopColor,
          borderTopLeftRadius: borderTopLeftRadius,
          borderTopRightRadius: borderTopRightRadius,
          borderTopStyle: borderTopStyle,
          borderTopWidth: borderTopWidth,
          borderWidth: borderWidth,
          bottom: bottom,
          boxShadow: boxShadow,
          boxSizing: boxSizing,
          breakAfter: breakAfter,
          breakBefore: breakBefore,
          breakInside: breakInside,
          bufferedRendering: bufferedRendering,
          captionSide: captionSide,
          caretColor: caretColor,
          clear: clear,
          clip: clip,
          clipPath: clipPath,
          clipRule: clipRule,
          color: color,
          colorInterpolation: colorInterpolation,
          colorInterpolationFilters: colorInterpolationFilters,
          colorRendering: colorRendering,
          colorScheme: colorScheme,
          columnCount: columnCount,
          columnFill: columnFill,
          columnGap: columnGap,
          columnRule: columnRule,
          columnRuleColor: columnRuleColor,
          columnRuleStyle: columnRuleStyle,
          columnRuleWidth: columnRuleWidth,
          columnSpan: columnSpan,
          columnWidth: columnWidth,
          columns: columns,
          contain: contain,
          containIntrinsicSize: containIntrinsicSize,
          content: content,
          contentVisibility: contentVisibility,
          counterIncrement: counterIncrement,
          counterReset: counterReset,
          counterSet: counterSet,
          cursor: cursor,
          cx: cx,
          cy: cy,
          d: d,
          descentOverride: descentOverride,
          direction: direction,
          display: display,
          dominantBaseline: dominantBaseline,
          emptyCells: emptyCells,
          end: end,
          fallback: fallback,
          fill: fill,
          fillOpacity: fillOpacity,
          fillRule: fillRule,
          filter: filter,
          flex: flex,
          flexBasis: flexBasis,
          flexDirection: flexDirection,
          flexFlow: flexFlow,
          flexGrow: flexGrow,
          flexShrink: flexShrink,
          flexWrap: flexWrap,
          float: float,
          floodColor: floodColor,
          floodOpacity: floodOpacity,
          font: font,
          fontDisplay: fontDisplay,
          fontFamily: fontFamily,
          fontFeatureSettings: fontFeatureSettings,
          fontKerning: fontKerning,
          fontOpticalSizing: fontOpticalSizing,
          fontSize: fontSize,
          fontStretch: fontStretch,
          fontStyle: fontStyle,
          fontVariant: fontVariant,
          fontVariantCaps: fontVariantCaps,
          fontVariantEastAsian: fontVariantEastAsian,
          fontVariantLigatures: fontVariantLigatures,
          fontVariantNumeric: fontVariantNumeric,
          fontVariationSettings: fontVariationSettings,
          fontWeight: fontWeight,
          forcedColorAdjust: forcedColorAdjust,
          gap: gap,
          grid: grid,
          gridArea: gridArea,
          gridAutoColumns: gridAutoColumns,
          gridAutoFlow: gridAutoFlow,
          gridAutoRows: gridAutoRows,
          gridColumn: gridColumn,
          gridColumnEnd: gridColumnEnd,
          gridColumnGap: gridColumnGap,
          gridColumnStart: gridColumnStart,
          gridGap: gridGap,
          gridRow: gridRow,
          gridRowEnd: gridRowEnd,
          gridRowGap: gridRowGap,
          gridRowStart: gridRowStart,
          gridTemplate: gridTemplate,
          gridTemplateAreas: gridTemplateAreas,
          gridTemplateColumns: gridTemplateColumns,
          gridTemplateRows: gridTemplateRows,
          height: height,
          hyphens: hyphens,
          imageOrientation: imageOrientation,
          imageRendering: imageRendering,
          inherits: inherits,
          initialValue: initialValue,
          inlineSize: inlineSize,
          inset: inset,
          insetBlock: insetBlock,
          insetBlockEnd: insetBlockEnd,
          insetBlockStart: insetBlockStart,
          insetInline: insetInline,
          insetInlineEnd: insetInlineEnd,
          insetInlineStart: insetInlineStart,
          isolation: isolation,
          justifyContent: justifyContent,
          justifyItems: justifyItems,
          justifySelf: justifySelf,
          left: left,
          letterSpacing: letterSpacing,
          lightingColor: lightingColor,
          lineBreak: lineBreak,
          lineGapOverride: lineGapOverride,
          lineHeight: lineHeight,
          lineHeightStep: lineHeightStep,
          listStyle: listStyle,
          listStyleImage: listStyleImage,
          listStylePosition: listStylePosition,
          listStyleType: listStyleType,
          margin: margin,
          marginBlock: marginBlock,
          marginBlockEnd: marginBlockEnd,
          marginBlockStart: marginBlockStart,
          marginBottom: marginBottom,
          marginInline: marginInline,
          marginInlineEnd: marginInlineEnd,
          marginInlineStart: marginInlineStart,
          marginLeft: marginLeft,
          marginRight: marginRight,
          marginTop: marginTop,
          marker: marker,
          markerEnd: markerEnd,
          markerMid: markerMid,
          markerStart: markerStart,
          mask: mask,
          maskType: maskType,
          mathDepth: mathDepth,
          mathShift: mathShift,
          mathStyle: mathStyle,
          maxBlockSize: maxBlockSize,
          maxHeight: maxHeight,
          maxInlineSize: maxInlineSize,
          maxWidth: maxWidth,
          maxZoom: maxZoom,
          minBlockSize: minBlockSize,
          minHeight: minHeight,
          minInlineSize: minInlineSize,
          minWidth: minWidth,
          minZoom: minZoom,
          mixBlendMode: mixBlendMode,
          negative: negative,
          objectFit: objectFit,
          objectPosition: objectPosition,
          offset: offset,
          offsetAnchor: offsetAnchor,
          offsetDistance: offsetDistance,
          offsetPath: offsetPath,
          offsetPosition: offsetPosition,
          offsetRotate: offsetRotate,
          opacity: opacity,
          order: order,
          orientation: orientation,
          orphans: orphans,
          outline: outline,
          outlineColor: outlineColor,
          outlineOffset: outlineOffset,
          outlineStyle: outlineStyle,
          outlineWidth: outlineWidth,
          overflow: overflow,
          overflowAnchor: overflowAnchor,
          overflowClipMargin: overflowClipMargin,
          overflowWrap: overflowWrap,
          overflowX: overflowX,
          overflowY: overflowY,
          overscrollBehavior: overscrollBehavior,
          overscrollBehaviorBlock: overscrollBehaviorBlock,
          overscrollBehaviorInline: overscrollBehaviorInline,
          overscrollBehaviorX: overscrollBehaviorX,
          overscrollBehaviorY: overscrollBehaviorY,
          pad: pad,
          padding: padding,
          paddingBlock: paddingBlock,
          paddingBlockEnd: paddingBlockEnd,
          paddingBlockStart: paddingBlockStart,
          paddingBottom: paddingBottom,
          paddingInline: paddingInline,
          paddingInlineEnd: paddingInlineEnd,
          paddingInlineStart: paddingInlineStart,
          paddingLeft: paddingLeft,
          paddingRight: paddingRight,
          paddingTop: paddingTop,
          page: page,
          pageBreakAfter: pageBreakAfter,
          pageBreakBefore: pageBreakBefore,
          pageBreakInside: pageBreakInside,
          pageOrientation: pageOrientation,
          paintOrder: paintOrder,
          perspective: perspective,
          perspectiveOrigin: perspectiveOrigin,
          placeContent: placeContent,
          placeItems: placeItems,
          placeSelf: placeSelf,
          pointerEvents: pointerEvents,
          position: position,
          prefix: prefix,
          quotes: quotes,
          r: r,
          range: range,
          resize: resize,
          right: right,
          rotate: rotate,
          rowGap: rowGap,
          rubyPosition: rubyPosition,
          rx: rx,
          ry: ry,
          scale: scale,
          scrollBehavior: scrollBehavior,
          scrollMargin: scrollMargin,
          scrollMarginBlock: scrollMarginBlock,
          scrollMarginBlockEnd: scrollMarginBlockEnd,
          scrollMarginBlockStart: scrollMarginBlockStart,
          scrollMarginBottom: scrollMarginBottom,
          scrollMarginInline: scrollMarginInline,
          scrollMarginInlineEnd: scrollMarginInlineEnd,
          scrollMarginInlineStart: scrollMarginInlineStart,
          scrollMarginLeft: scrollMarginLeft,
          scrollMarginRight: scrollMarginRight,
          scrollMarginTop: scrollMarginTop,
          scrollPadding: scrollPadding,
          scrollPaddingBlock: scrollPaddingBlock,
          scrollPaddingBlockEnd: scrollPaddingBlockEnd,
          scrollPaddingBlockStart: scrollPaddingBlockStart,
          scrollPaddingBottom: scrollPaddingBottom,
          scrollPaddingInline: scrollPaddingInline,
          scrollPaddingInlineEnd: scrollPaddingInlineEnd,
          scrollPaddingInlineStart: scrollPaddingInlineStart,
          scrollPaddingLeft: scrollPaddingLeft,
          scrollPaddingRight: scrollPaddingRight,
          scrollPaddingTop: scrollPaddingTop,
          scrollSnapAlign: scrollSnapAlign,
          scrollSnapStop: scrollSnapStop,
          scrollSnapType: scrollSnapType,
          scrollbarGutter: scrollbarGutter,
          shapeImageThreshold: shapeImageThreshold,
          shapeMargin: shapeMargin,
          shapeOutside: shapeOutside,
          shapeRendering: shapeRendering,
          size: size,
          sizeAdjust: sizeAdjust,
          source: source,
          speak: speak,
          speakAs: speakAs,
          src: src,
          start: start,
          stopColor: stopColor,
          stopOpacity: stopOpacity,
          stroke: stroke,
          strokeDasharray: strokeDasharray,
          strokeDashoffset: strokeDashoffset,
          strokeLinecap: strokeLinecap,
          strokeLinejoin: strokeLinejoin,
          strokeMiterlimit: strokeMiterlimit,
          strokeOpacity: strokeOpacity,
          strokeWidth: strokeWidth,
          suffix: suffix,
          symbols: symbols,
          syntax: syntax,
          system: system,
          tabSize: tabSize,
          tableLayout: tableLayout,
          textAlign: textAlign,
          textAlignLast: textAlignLast,
          textAnchor: textAnchor,
          textCombineUpright: textCombineUpright,
          textDecoration: textDecoration,
          textDecorationColor: textDecorationColor,
          textDecorationLine: textDecorationLine,
          textDecorationSkipInk: textDecorationSkipInk,
          textDecorationStyle: textDecorationStyle,
          textDecorationThickness: textDecorationThickness,
          textIndent: textIndent,
          textJustify: textJustify,
          textOrientation: textOrientation,
          textOverflow: textOverflow,
          textRendering: textRendering,
          textShadow: textShadow,
          textSizeAdjust: textSizeAdjust,
          textTransform: textTransform,
          textUnderlineOffset: textUnderlineOffset,
          textUnderlinePosition: textUnderlinePosition,
          timeRange: timeRange,
          top: top,
          touchAction: touchAction,
          transform: transform,
          transformBox: transformBox,
          transformOrigin: transformOrigin,
          transformStyle: transformStyle,
          transition: transition,
          transitionDelay: transitionDelay,
          transitionDuration: transitionDuration,
          transitionProperty: transitionProperty,
          transitionTimingFunction: transitionTimingFunction,
          translate: translate,
          unicodeBidi: unicodeBidi,
          unicodeRange: unicodeRange,
          userSelect: userSelect,
          userZoom: userZoom,
          vectorEffect: vectorEffect,
          verticalAlign: verticalAlign,
          visibility: visibility,
          webkitAlignContent: webkitAlignContent,
          webkitAlignItems: webkitAlignItems,
          webkitAlignSelf: webkitAlignSelf,
          webkitAnimation: webkitAnimation,
          webkitAnimationDelay: webkitAnimationDelay,
          webkitAnimationDirection: webkitAnimationDirection,
          webkitAnimationDuration: webkitAnimationDuration,
          webkitAnimationFillMode: webkitAnimationFillMode,
          webkitAnimationIterationCount: webkitAnimationIterationCount,
          webkitAnimationName: webkitAnimationName,
          webkitAnimationPlayState: webkitAnimationPlayState,
          webkitAnimationTimingFunction: webkitAnimationTimingFunction,
          webkitAppRegion: webkitAppRegion,
          webkitAppearance: webkitAppearance,
          webkitBackfaceVisibility: webkitBackfaceVisibility,
          webkitBackgroundClip: webkitBackgroundClip,
          webkitBackgroundOrigin: webkitBackgroundOrigin,
          webkitBackgroundSize: webkitBackgroundSize,
          webkitBorderAfter: webkitBorderAfter,
          webkitBorderAfterColor: webkitBorderAfterColor,
          webkitBorderAfterStyle: webkitBorderAfterStyle,
          webkitBorderAfterWidth: webkitBorderAfterWidth,
          webkitBorderBefore: webkitBorderBefore,
          webkitBorderBeforeColor: webkitBorderBeforeColor,
          webkitBorderBeforeStyle: webkitBorderBeforeStyle,
          webkitBorderBeforeWidth: webkitBorderBeforeWidth,
          webkitBorderBottomLeftRadius: webkitBorderBottomLeftRadius,
          webkitBorderBottomRightRadius: webkitBorderBottomRightRadius,
          webkitBorderEnd: webkitBorderEnd,
          webkitBorderEndColor: webkitBorderEndColor,
          webkitBorderEndStyle: webkitBorderEndStyle,
          webkitBorderEndWidth: webkitBorderEndWidth,
          webkitBorderHorizontalSpacing: webkitBorderHorizontalSpacing,
          webkitBorderImage: webkitBorderImage,
          webkitBorderRadius: webkitBorderRadius,
          webkitBorderStart: webkitBorderStart,
          webkitBorderStartColor: webkitBorderStartColor,
          webkitBorderStartStyle: webkitBorderStartStyle,
          webkitBorderStartWidth: webkitBorderStartWidth,
          webkitBorderTopLeftRadius: webkitBorderTopLeftRadius,
          webkitBorderTopRightRadius: webkitBorderTopRightRadius,
          webkitBorderVerticalSpacing: webkitBorderVerticalSpacing,
          webkitBoxAlign: webkitBoxAlign,
          webkitBoxDecorationBreak: webkitBoxDecorationBreak,
          webkitBoxDirection: webkitBoxDirection,
          webkitBoxFlex: webkitBoxFlex,
          webkitBoxOrdinalGroup: webkitBoxOrdinalGroup,
          webkitBoxOrient: webkitBoxOrient,
          webkitBoxPack: webkitBoxPack,
          webkitBoxReflect: webkitBoxReflect,
          webkitBoxShadow: webkitBoxShadow,
          webkitBoxSizing: webkitBoxSizing,
          webkitClipPath: webkitClipPath,
          webkitColumnBreakAfter: webkitColumnBreakAfter,
          webkitColumnBreakBefore: webkitColumnBreakBefore,
          webkitColumnBreakInside: webkitColumnBreakInside,
          webkitColumnCount: webkitColumnCount,
          webkitColumnGap: webkitColumnGap,
          webkitColumnRule: webkitColumnRule,
          webkitColumnRuleColor: webkitColumnRuleColor,
          webkitColumnRuleStyle: webkitColumnRuleStyle,
          webkitColumnRuleWidth: webkitColumnRuleWidth,
          webkitColumnSpan: webkitColumnSpan,
          webkitColumnWidth: webkitColumnWidth,
          webkitColumns: webkitColumns,
          webkitFilter: webkitFilter,
          webkitFlex: webkitFlex,
          webkitFlexBasis: webkitFlexBasis,
          webkitFlexDirection: webkitFlexDirection,
          webkitFlexFlow: webkitFlexFlow,
          webkitFlexGrow: webkitFlexGrow,
          webkitFlexShrink: webkitFlexShrink,
          webkitFlexWrap: webkitFlexWrap,
          webkitFontFeatureSettings: webkitFontFeatureSettings,
          webkitFontSmoothing: webkitFontSmoothing,
          webkitHighlight: webkitHighlight,
          webkitHyphenateCharacter: webkitHyphenateCharacter,
          webkitJustifyContent: webkitJustifyContent,
          webkitLineBreak: webkitLineBreak,
          webkitLineClamp: webkitLineClamp,
          webkitLocale: webkitLocale,
          webkitLogicalHeight: webkitLogicalHeight,
          webkitLogicalWidth: webkitLogicalWidth,
          webkitMarginAfter: webkitMarginAfter,
          webkitMarginBefore: webkitMarginBefore,
          webkitMarginEnd: webkitMarginEnd,
          webkitMarginStart: webkitMarginStart,
          webkitMask: webkitMask,
          webkitMaskBoxImage: webkitMaskBoxImage,
          webkitMaskBoxImageOutset: webkitMaskBoxImageOutset,
          webkitMaskBoxImageRepeat: webkitMaskBoxImageRepeat,
          webkitMaskBoxImageSlice: webkitMaskBoxImageSlice,
          webkitMaskBoxImageSource: webkitMaskBoxImageSource,
          webkitMaskBoxImageWidth: webkitMaskBoxImageWidth,
          webkitMaskClip: webkitMaskClip,
          webkitMaskComposite: webkitMaskComposite,
          webkitMaskImage: webkitMaskImage,
          webkitMaskOrigin: webkitMaskOrigin,
          webkitMaskPosition: webkitMaskPosition,
          webkitMaskPositionX: webkitMaskPositionX,
          webkitMaskPositionY: webkitMaskPositionY,
          webkitMaskRepeat: webkitMaskRepeat,
          webkitMaskRepeatX: webkitMaskRepeatX,
          webkitMaskRepeatY: webkitMaskRepeatY,
          webkitMaskSize: webkitMaskSize,
          webkitMaxLogicalHeight: webkitMaxLogicalHeight,
          webkitMaxLogicalWidth: webkitMaxLogicalWidth,
          webkitMinLogicalHeight: webkitMinLogicalHeight,
          webkitMinLogicalWidth: webkitMinLogicalWidth,
          webkitOpacity: webkitOpacity,
          webkitOrder: webkitOrder,
          webkitPaddingAfter: webkitPaddingAfter,
          webkitPaddingBefore: webkitPaddingBefore,
          webkitPaddingEnd: webkitPaddingEnd,
          webkitPaddingStart: webkitPaddingStart,
          webkitPerspective: webkitPerspective,
          webkitPerspectiveOrigin: webkitPerspectiveOrigin,
          webkitPerspectiveOriginX: webkitPerspectiveOriginX,
          webkitPerspectiveOriginY: webkitPerspectiveOriginY,
          webkitPrintColorAdjust: webkitPrintColorAdjust,
          webkitRtlOrdering: webkitRtlOrdering,
          webkitRubyPosition: webkitRubyPosition,
          webkitShapeImageThreshold: webkitShapeImageThreshold,
          webkitShapeMargin: webkitShapeMargin,
          webkitShapeOutside: webkitShapeOutside,
          webkitTapHighlightColor: webkitTapHighlightColor,
          webkitTextCombine: webkitTextCombine,
          webkitTextDecorationsInEffect: webkitTextDecorationsInEffect,
          webkitTextEmphasis: webkitTextEmphasis,
          webkitTextEmphasisColor: webkitTextEmphasisColor,
          webkitTextEmphasisPosition: webkitTextEmphasisPosition,
          webkitTextEmphasisStyle: webkitTextEmphasisStyle,
          webkitTextFillColor: webkitTextFillColor,
          webkitTextOrientation: webkitTextOrientation,
          webkitTextSecurity: webkitTextSecurity,
          webkitTextSizeAdjust: webkitTextSizeAdjust,
          webkitTextStroke: webkitTextStroke,
          webkitTextStrokeColor: webkitTextStrokeColor,
          webkitTextStrokeWidth: webkitTextStrokeWidth,
          webkitTransform: webkitTransform,
          webkitTransformOrigin: webkitTransformOrigin,
          webkitTransformOriginX: webkitTransformOriginX,
          webkitTransformOriginY: webkitTransformOriginY,
          webkitTransformOriginZ: webkitTransformOriginZ,
          webkitTransformStyle: webkitTransformStyle,
          webkitTransition: webkitTransition,
          webkitTransitionDelay: webkitTransitionDelay,
          webkitTransitionDuration: webkitTransitionDuration,
          webkitTransitionProperty: webkitTransitionProperty,
          webkitTransitionTimingFunction: webkitTransitionTimingFunction,
          webkitUserDrag: webkitUserDrag,
          webkitUserModify: webkitUserModify,
          webkitUserSelect: webkitUserSelect,
          webkitWritingMode: webkitWritingMode,
          whiteSpace: whiteSpace,
          widows: widows,
          width: width,
          willChange: willChange,
          wordBreak: wordBreak,
          wordSpacing: wordSpacing,
          wordWrap: wordWrap,
          writingMode: writingMode,
          x: x,
          y: y,
          zIndex: zIndex,
          zoom: zoom,
          cssText: cssText,
          length: length,
          parentRule: parentRule,
          cssFloat: cssFloat,
          getPropertyPriority: getPropertyPriority,
          getPropertyValue: getPropertyValue,
          item: item,
          removeProperty: removeProperty,
          setProperty: setProperty,
     };
};
