import { CreateComponent } from "../../../index.js";

export default ({
    accept,
    alt,
    autoComplete,
    capture,
    checked,
    dirName,
    disabled,
    form,
    formAction,
    formEncType,
    formMethod,
    formNoValidate,
    formTarget,
    height,
    list,
    max,
    maxLength,
    min,
    minLength,
    multiple,
    name,
    pattern,
    placeholder,
    readOnly,
    required,
    size,
    src,
    step,
    type,
    value,
    width,
    props,
    key,
    events,
    hooks,
    style,
    flags,
}) => {
    return new CreateComponent({
        tag: "input",
        data: { value },
        props: {
            ...props,
            accept,
            alt,
            autoComplete,
            capture,
            checked,
            dirName,
            disabled,
            form,
            formAction,
            formEncType,
            formMethod,
            formNoValidate,
            formTarget,
            height,
            list,
            max,
            maxLength,
            min,
            minLength,
            multiple,
            name,
            pattern,
            placeholder,
            readOnly,
            required,
            size,
            src,
            step,
            type,
            value,
            width,
        },
        key,
        events,
        hooks,
        style,
        flags,
    });
};
