/**
 * @credit MDN (2022) - https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
 */
export default {
    accept: "accept",
    acceptCharSet: "acceptcharset",
    accessKey: "accesskey",
    abbr: "abbr",
    align: "align",
    allow: "allow",
    alt: "alt",
    async: "async",
    autoCapitalize: "autocapitalize",
    autoComplete: "autocomplete",
    autoFocus: "autofocus",
    autoplay: "autoplay",
    allowFullScreen: "allowfullscreen",
    allowPaymentRequest: "allowpaymentrequest",
    action: "action",

    background: "background",
    bgColor: "bgcolor",
    border: "border",
    buffered: "buffered",

    capture: "capture",
    challenge: "challenge",
    charSet: "charset",
    checked: "checked",
    cite: "cite",
    className: "className",
    code: "code",
    codeBase: "codebase",
    color: "color",
    cols: "cols",
    colSpan: "colSpan",
    contentEditable: "contenteditable",
    contextMenu: "contextmenu",
    controls: "controls",
    coords: "coords",
    crossOrigin: "crossorigin",
    csp: "csp",

    data: "data",
    dateTime: "datetime",
    decoding: "decoding",
    default: "default",
    defer: "defer",
    dir: "dir",
    dirName: "dirname",
    disabled: "disabled",
    download: "download",
    draggable: "draggable",

    encType: "enctype",
    entryKeyHint: "entrykeyhint",

    form: "form",
    formAction: "formaction",
    formEncType: "formenctype",
    formMethod: "formmethod",
    formNoValidate: "formnovalidate",
    formTarget: "formtarget",
    for: "for",

    headers: "headers",
    height: "height",
    hidden: "hidden",
    high: "high",
    href: "href",
    hrefLang: "hreflang",
    httpEquiv: "httpEquiv",

    icon: "icon",
    id: "id",
    importance: "importance",
    integrity: "integrity",
    intrinsicSize: "instrinsicsize",
    inputMode: "inputmode",
    isMap: "ismap",
    itemProp: "itemprop",

    kind: "kind",

    label: "label",
    lang: "lang",
    language: "language",
    loading: "loading",
    list: "list",
    loop: "loop",
    low: "low",

    manifest: "manifest",
    max: "max",
    maxLength: "maxLength",
    minLength: "minLength",
    media: "media",
    method: "method",
    min: "min",
    multiple: "multiple",
    muted: "muted",

    name: "name",
    noValidate: "novalidate",

    open: "open",
    optimum: "optimum",

    pattern: "pattern",
    ping: "ping",
    placeholder: "placeholder",
    poster: "poster",
    preload: "preload",

    radioGroup: "radiogroup",
    readOnly: "readonly",
    referrerPolicy: "referrerpolicy",
    rel: "rel",
    required: "required",
    reversed: "reversed",
    role: "role",
    rows: "rows",
    rowsSpan: "rowsspan",

    sandbox: "sandbox",
    scope: "scope",
    selected: "selected",
    shape: "shape",
    size: "size",
    sizes: "sizes",
    slot: "slot",
    span: "span",
    spellCheck: "spellcheck",
    src: "src",
    srcDoc: "srcdoc",
    srcSet: "srcset",
    start: "start",
    step: "step",
    summary: "summary",

    tabIndex: "tabindex",
    target: "target",
    title: "title",
    translate: "translate",
    type: "type",

    useMap: "usemap",

    value: "value",

    width: "width",
    wrap: "wrap",
};
