// Router
const ROUTER_DYNAMIC_REG_EXP = /:[^:;]*;/g;
const ROUTER_ANCHOR_REG_EXP = /#[\w.~:?#[\]@!$&'()*+,;=-]+$/;
const ROUTER_PATH_STATE = "router-path";
const ROUTER_ROUTE_STATE = "router-route";
const ROUTER_ANCHOR_STATE = "router-anchor";
const ROUTER_NOT_FOUND_ROUTE = "/404";

// DEVELOPMENT
const DEVELOPMENT_MODE = "development";

// ORCHESTRATOR
const ORCHESTRATOR_FREE = "free";
const ORCHESTRATOR_HANDLING_REQUESTS = "handling-requests";
const ORCHESTRATOR_COMPUTE_TREE = "calculating-tree";
const ORCHESTRATOR_COMPUTE_STYLE = "calculating-style";
const ORCHESTRATOR_RENDERING = "rendering";
const ORCHESTRATOR_UPDATING = "updating";
const ORCHESTRATOR_COMPUTE_DIFF = "calculating-diff";
const ORCHESTRATOR_EXEC_BEFORE_DESTROYED = "execute-before-destroyed";
const ORCHESTRATOR_COMMIT_INTO_TREE = "commit-into-tree";
const ORCHESTRATOR_EXEC_ON_DESTROYED = "execute-on-destroyed";
const ORCHESTRATOR_EXEC_ON_CREATED = "execute-on-created";
const ORCHESTRATOR_EXEC_ON_UPDATED = "execute-on-updated";
const ORCHESTRATOR_CLEAN_STATES = "clean-states";

// RENDERER
const FLAGS_FORCE_RERENDER = "forceRerender";
const FLAGS_RENDER_IF = "renderIf";

const HOOKS_ON_CREATED = "onCreated";
const HOOKS_ON_UPDATED = "onUpdated";
const HOOKS_ON_DESTROYED = "onDestroyed";
const HOOKS_ON_REF = "onRef";
const HOOKS_BEFORE_DESTROYED = "beforeDestroyed";
const HOOKS_BEFORE_PREPARED = "beforePrepared";
const HOOKS_ON_PREPARED = "onPrepared";

const ELEMENT_TYPE_FRAGMENT = "fragment";
const ELEMENT_TYPE_TEXT_NODE = "#text";
const ELEMENT_TYPE_RAW = "#raw";

const RENDERER_PHASE_ON_CREATED = "onCreated";
const RENDERER_PHASE_ON_UPDATED = "onUpdated";
const RENDERER_PHASE_ON_DESTROYED = "onDestroyed";
const RENDERER_PHASE_BEFORE_DESTROYED = "beforeDestroyed";
const RENDERER_PHASE_CHANGES = "changes";

const RECURSIVE_ELEMENT_SYMBOL = Symbol.for("recursive.element");

// STATE

const STATE_STATE_STORE = "state";
const STATE_CACHE_STORE = "cache";
const STATE_REF_STORE = "ref";
const STATE_RESERVED_STORE = "reserved";
const STATE_EFFECT_STORE = "effect";

module.exports = {
    STATE_CACHE_STORE,
    STATE_REF_STORE,
    STATE_RESERVED_STORE,
    STATE_STATE_STORE,
    STATE_EFFECT_STORE,

    ROUTER_ANCHOR_REG_EXP,
    ROUTER_DYNAMIC_REG_EXP,
    ROUTER_PATH_STATE,
    ROUTER_ROUTE_STATE,
    ROUTER_ANCHOR_STATE,
    ROUTER_NOT_FOUND_ROUTE,

    DEVELOPMENT_MODE,

    ORCHESTRATOR_FREE,
    ORCHESTRATOR_HANDLING_REQUESTS,
    ORCHESTRATOR_COMPUTE_TREE,
    ORCHESTRATOR_COMPUTE_STYLE,
    ORCHESTRATOR_RENDERING,
    ORCHESTRATOR_UPDATING,
    ORCHESTRATOR_COMPUTE_DIFF,
    ORCHESTRATOR_EXEC_BEFORE_DESTROYED,
    ORCHESTRATOR_COMMIT_INTO_TREE,
    ORCHESTRATOR_EXEC_ON_DESTROYED,
    ORCHESTRATOR_EXEC_ON_CREATED,
    ORCHESTRATOR_EXEC_ON_UPDATED,
    ORCHESTRATOR_CLEAN_STATES,

    FLAGS_FORCE_RERENDER,
    FLAGS_RENDER_IF,

    HOOKS_BEFORE_DESTROYED,
    HOOKS_ON_CREATED,
    HOOKS_ON_DESTROYED,
    HOOKS_ON_REF,
    HOOKS_ON_UPDATED,
    HOOKS_BEFORE_PREPARED,
    HOOKS_ON_PREPARED,

    ELEMENT_TYPE_FRAGMENT,
    ELEMENT_TYPE_TEXT_NODE,
    ELEMENT_TYPE_RAW,

    RENDERER_PHASE_BEFORE_DESTROYED,
    RENDERER_PHASE_CHANGES,
    RENDERER_PHASE_ON_CREATED,
    RENDERER_PHASE_ON_DESTROYED,
    RENDERER_PHASE_ON_UPDATED,

    RECURSIVE_ELEMENT_SYMBOL,
};
