import CreateComponent from "../CreateComponent.js";

export default ({
     text,
     placeholder,
     style,
     styleSheet,
     id,
     className,
     events,
     autofocus,
     cols,
     dirname,
     disabled,
     form,
     maxLength,
     name,
     readOnly,
     required,
     rows,
     wrap,
     onCreated,
     beforeDestroyed,
     onDestroyed,
     onUpdated,
     onStateUpdated,
}) =>
     new CreateComponent({
          tag: "textarea",
          children: text,
          onCreated,
          autofocus: autofocus,
          cols: cols,
          style: styleSheet,
          dirname: dirname,
          disabled: disabled,
          form: form,
          maxLength: maxLength,
          name: name,
          readOnly: readOnly,
          required: required,
          rows: rows,
          wrap: wrap,
          placeholder: placeholder,
          inlineStyle: style,
          id: id,
          className: className,
          events: events,
          onCreated,
          beforeDestroyed,
          onDestroyed,
          onUpdated,
          onStateUpdated,
     });
