import CreateComponent from "../CreateComponent.js";

export default ({
     text,
     placeholder,
     style,
     id,
     className,
     events,
     autofocus,
     cols,
     dirname,
     disabled,
     form,
     maxLength,
     name,
     readOnly,
     required,
     rows,
     wrap,
}) =>
     new CreateComponent({
          tag: "textarea",
          children: text,
          autofocus: autofocus,
          cols: cols,
          dirname: dirname,
          disabled: disabled,
          form: form,
          maxLength: maxLength,
          name: name,
          readOnly: readOnly,
          required: required,
          rows: rows,
          wrap: wrap,
          placeholder: placeholder,
          inlineStyle: style,
          id: id,
          className: className,
          events: events,
     });
