import CreateComponent from "../CreateComponent.js";

const template = ({ type, name, value, style, id, className, events, min, max }) =>
     new CreateComponent({
          tag: "input",
          type: type,
          name: name,
          vale: value,
          inlineStyle: style,
          id: id,
          className: className,
          events: events,
          min: min,
          max: max,
     });

export default {
     CheckBox: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "checkbox",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
     Date: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "date",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
     DateTimeLocal: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "datetime-local",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
     Email: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "email",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
     File: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "file",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
     Image: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "image",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
     Month: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "month",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
     Number: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "number",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
     Password: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "password",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
     Radio: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "radio",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
     Range: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "range",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
     Text: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "text",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
     Telephone: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "telephone",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
     Time: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "time",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
     URL: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "url",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
     Week: ({ name, value, style, id, className, events, min, max }) =>
          template({
               type: "week",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
          }),
};
