import CreateComponent from "../CreateComponent.js";

const template = ({
     type,
     name,
     value,
     style,
     id,
     className,
     events,
     min,
     max,
     placeholder,
     onCreated,
     onDestroyed,
     onUpdated,
     beforeCreated,
     beforeDestroyed,
}) =>
     new CreateComponent({
          tag: "input",
          type: type,
          name: name,
          value: value,
          inlineStyle: style,
          id: id,
          className: className,
          events: events,
          min: min,
          max: max,
          placeholder: placeholder,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     });

export default {
     CheckBox: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          max,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "checkbox",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
          }),
     Date: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          max,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "date",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
          }),
     DateTimeLocal: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          max,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "datetime-local",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
          }),
     Email: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          max,
          placeholder,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "email",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               placeholder: placeholder,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
          }),
     File: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          max,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "file",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
          }),
     Image: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          max,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "image",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
               onCreated,
          }),
     Month: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          max,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "month",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
          }),
     Number: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          max,
          placeholder,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "number",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               placeholder: placeholder,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
               onCreated,
          }),
     Password: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          max,
          placeholder,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "password",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               placeholder: placeholder,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
               onCreated,
          }),
     Radio: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "radio",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
          }),
     Range: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          max,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "range",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
          }),
     Text: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          max,
          placeholder,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "text",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               placeholder: placeholder,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
          }),
     Telephone: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          max,
          placeholder,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "telephone",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               placeholder: placeholder,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
          }),
     Time: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          max,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "time",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
          }),
     URL: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          max,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "url",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
               onCreated,
          }),
     Week: ({
          name,
          value,
          style,
          id,
          className,
          events,
          min,
          max,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
     }) =>
          template({
               type: "week",
               name: name,
               value: value,
               style: style,
               id: id,
               className: className,
               events: events,
               min: min,
               max: max,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
          }),
};
