import CreateComponent from "../CreateComponent.js";

const hn = ({
     hn,
     text,
     id,
     style,
     events,
     className,
     onCreated,
     onDestroyed,
     styleSheet,
     onUpdated,
     beforeCreated,
     beforeDestroyed,
     onRefreshed,
}) =>
     new CreateComponent({
          tag: hn,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
          children: text,
          style: styleSheet,
          id: id,
          inlineStyle: style,
          events: events,
          className: className,
          onCreated,
          onRefreshed,
     });

export default {
     h1: ({
          text,
          id,
          style,
          events,
          className,
          styleSheet,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
          onRefreshed,
     }) =>
          hn({
               hn: "h1",
               text: text,
               id: id,
               style: style,
               styleSheet,
               events: events,
               className: className,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
               onRefreshed,
          }),
     h2: ({
          text,
          id,
          style,
          events,
          className,
          styleSheet,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
          onRefreshed,
     }) =>
          hn({
               hn: "h2",
               text: text,
               id: id,
               styleSheet,
               style: style,
               events: events,
               className: className,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
               onRefreshed,
          }),
     h3: ({
          text,
          id,
          style,
          events,
          className,
          styleSheet,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
          onRefreshed,
     }) =>
          hn({
               hn: "h3",
               text: text,
               id: id,
               styleSheet,
               style: style,
               events: events,
               className: className,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
               onCreated,
               onRefreshed,
          }),
     h4: ({
          text,
          id,
          style,
          events,
          styleSheet,
          className,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
          onRefreshed,
     }) =>
          hn({
               hn: "h4",
               text: text,
               id: id,
               style: style,
               styleSheet,
               events: events,
               className: className,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
               onRefreshed,
          }),
     h5: ({
          text,
          id,
          style,
          events,
          styleSheet,
          className,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
          onRefreshed,
     }) =>
          hn({
               hn: "h5",
               text: text,
               id: id,
               style: style,
               events: events,
               className: className,
               styleSheet,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
               onRefreshed,
          }),
     h6: ({
          text,
          id,
          style,
          events,
          className,
          styleSheet,
          onCreated,
          onDestroyed,
          onUpdated,
          beforeCreated,
          beforeDestroyed,
          onRefreshed,
     }) =>
          hn({
               hn: "h6",
               text: text,
               id: id,
               styleSheet,
               style: style,
               events: events,
               className: className,
               onCreated,
               onDestroyed,
               onUpdated,
               beforeCreated,
               beforeDestroyed,
               onRefreshed,
          }),
};
