import CreateComponent from "../../CreateComponent.js";

export default ({
     children,
     style,
     styleSheet,
     id,
     download,
     href,
     hrefLang,
     ping,
     referrerPolicy,
     rel,
     target,
     type,
     charSet,
     coords,
     name,
     rev,
     shape,
     className,
     events,
     renderIf = true,
     hooks,
}) =>
     new CreateComponent({
          tag: "a",
          children: children,
          inlineStyle: style,
          props: {
               id,
               download,
               href,
               hrefLang,
               ping,
               referrerPolicy,
               rev,
               target,
               rel,
               type,
               charSet,
               coords,
               name,
               shape,
          },
          renderIf,
          className: className,
          events: events,
          hooks,
          style: styleSheet,
     });
