import CreateComponent from "../../CreateComponent.js";

export default ({
     children,
     style,
     styleSheet,
     id,
     allow,
     allowFullScreen,
     allowPaymentRequest,
     height,
     loading,
     name,
     referrerPolicy,
     sandbox,
     src,
     srcDoc,
     width,
     className,
     events,
     renderIf = true,
     hooks,
}) =>
     new CreateComponent({
          children,
          tag: "iframe",
          inlineStyle: style,
          renderIf,
          props: {
               id,
               allow,
               allowFullScreen,
               allowPaymentRequest,
               height,
               loading,
               name,
               referrerPolicy,
               sandbox,
               src,
               srcDoc,
               width,
          },
          className: className,
          events: events,
          hooks,
          style: styleSheet,
     });
