const event = new Event("click");

/**
 * @param {typeof event} event
 */
const listener = (event) => {};

export default {
    onAbort: listener,
    onAutoComplete: listener,
    onAutoCompleteError: listener,
    onBlur: listener,
    onCancel: listener,
    onCanPlay: listener,
    onCanPlayThrough: listener,
    onChange: listener,
    onClick: listener,
    onClose: listener,
    onContextMenu: listener,
    onCueChange: listener,
    onDblClick: listener,
    onDrag: listener,
    onDragEnd: listener,
    onDragEnter: listener,
    onDragLeave: listener,
    onDragOver: listener,
    onDragStart: listener,
    onDrop: listener,
    onDurationChange: listener,
    onEmptied: listener,
    onEnded: listener,
    onError: listener,
    onFocus: listener,
    onInput: listener,
    onInvalid: listener,
    onKeyDown: listener,
    onKeyPress: listener,
    onKeyUp: listener,
    onLoad: listener,
    onLoadedData: listener,
    onLoadedMetadata: listener,
    onLoadStart: listener,
    onMouseDown: listener,
    onMouseEnter: listener,
    onMouseLeave: listener,
    onMouseMove: listener,
    onMouseOut: listener,
    onMouseOver: listener,
    onMouseUp: listener,
    onMouseWheel: listener,
    onPause: listener,
    onPlay: listener,
    onPlaying: listener,
    onProgress: listener,
    onRatechange: listener,
    onReset: listener,
    onResize: listener,
    onScroll: listener,
    onSeeked: listener,
    onSeeking: listener,
    onSelect: listener,
    onShow: listener,
    onSort: listener,
    onStalled: listener,
    onSubmit: listener,
    onSuspend: listener,
    onTimeUpdate: listener,
    onToggle: listener,
    onVolumeChange: listener,
    onWaiting: listener,

    onActivate: listener,
    onFocusIn: listener,
    onFocusOut: listener,

    onBegin: listener,
    onEnd: listener,
    onRepeat: listener,

    onCopy: listener,
    onCut: listener,
    onPaste: listener,
};
