export default {
    accessKey: "",
    autoCapitalize: "",
    autoFocus: "",
    className: "",
    contentEditable: false,
    contextMenu: "",
    dataSet: "",
    dir: "",
    draggable: "",
    enterKeyHint: "",
    exportParts: "",
    hidden: "",
    id: "",
    inputMode: "",
    is: "",
    itemId: "",
    itemProp: "",
    lang: "",
    nonce: "",
    part: "",
    slot: "",
    spellCheck: "",
    tabIndex: "",
    title: "",
    translate: "",
};
