import CreateComponent from "../../CreateComponent.js";

export default ({
     text,
     style,
     styleSheet,
     id,
     autofocus,
     disabled,
     form,
     formAction,
     formEncType,
     formMethod,
     formNoValidate,
     formTarget,
     name,
     type,
     value,
     className,
     events,
     renderIf = true,
     hooks,
}) =>
     new CreateComponent({
          children: text,
          tag: "button",
          inlineStyle: style,
          renderIf,
          props: {
               id,
               autofocus,
               disabled,
               form,
               formAction,
               formEncType,
               formMethod,
               formNoValidate,
               formTarget,
               name,
               type,
               value,
          },
          className: className,
          events: events,
          hooks,
          style: styleSheet,
     });
