import CreateComponent from "../../CreateComponent.js";

export default ({
     style,
     styleSheet,
     id,
     className,
     events,
     renderIf = true,
     hooks,
     accept,
     alt,
     autoComplete,
     autofocus,
     capture,
     checked,
     dirname,
     disabled,
     form,
     formAction,
     formEncType,
     formMethod,
     formNoValidate,
     formTarget,
     height,
     list,
     max,
     maxLength,
     min,
     minLength,
     multiple,
     name,
     pattern,
     placeholder,
     readOnly,
     required,
     size,
     src,
     step,
     type,
     value,
     width,
}) =>
     new CreateComponent({
          tag: "input",
          inlineStyle: style,
          renderIf,
          props: {
               id,
               type,
               accept,
               alt,
               autoComplete,
               autofocus,
               capture,
               checked,
               dirname,
               disabled,
               form,
               formAction,
               formEncType,
               formMethod,
               formNoValidate,
               formTarget,
               height,
               list,
               max,
               maxLength,
               min,
               minLength,
               multiple,
               name,
               pattern,
               placeholder,
               readOnly,
               required,
               size,
               src,
               step,
               value,
               width,
          },
          className: className,
          events: events,
          hooks,
          style: styleSheet,
     });
