import CreateComponent from "../../CreateComponent.js";

export default ({
     text,
     style,
     styleSheet,
     id,
     autoComplete,
     autofocus,
     cols,
     disabled,
     form,
     maxLength,
     minLength,
     name,
     placeholder,
     readOnly,
     required,
     rows,
     spellCheck,
     wrap,
     className,
     events,
     renderIf = true,
     hooks,
}) =>
     new CreateComponent({
          children: text,
          tag: "textarea",
          inlineStyle: style,
          renderIf,
          props: {
               id,
               autoComplete,
               autofocus,
               cols,
               disabled,
               form,
               maxLength,
               minLength,
               name,
               placeholder,
               readOnly,
               required,
               rows,
               spellCheck,
               wrap,
          },
          className: className,
          events: events,
          hooks,
          style: styleSheet,
     });
