export default {
     autoFocus: "autofocus",
     abbreviation: "abbr",
     align: "align",
     alt: "alt",
     allow: "allow",
     allowFullScreen: "allowfullscreen",
     allowPaymentRequest: "allowpaymentrequest",
     accept: "accept",
     autoComplete: "autocomplete",
     autoplay: "autoplay",
     acceptCharSet: "acceptcharset",
     action: "action",

     cols: "cols",
     color: "color",
     className: "className",
     controls: "controls",
     cite: "cite",
     crossOrigin: "crossorigin",
     coords: "coords",
     checked: "checked",
     charSet: "charset",
     colSpan: "colSpan",

     data: "data",
     dirName: "dirname",
     dir: "dir",
     disabled: "disabled",
     dateTime: "datetime",
     download: "download",
     decoding: "decoding",
     default: "default",

     encType: "enctype",

     form: "form",
     formAction: "formaction",
     formEncType: "formenctype",
     formMethod: "formmethod",
     formNoValidate: "formnovalidate",
     formTarget: "formtarget",
     isFor: "for",

     href: "href",
     hrefLang: "hreflang",
     height: "height",
     high: "high",
     headers: "headers",

     id: "id",
     isMap: "ismap",

     kind: "kind",

     loop: "loop",
     list: "list",
     loading: "loading",
     longDesc: "longdesc",
     low: "low",
     label: "label",

     max: "max",
     min: "min",
     media: "media",
     maxLength: "maxLength",
     minLength: "minLength",
     muted: "muted",
     multiple: "multiple",
     method: "method",

     name: "name",
     noValidate: "novalidate",
     noWrap: "nowrap",
     noShade: "noshade",

     open: "open",
     optimum: "optimum",

     placeholder: "placeholder",
     ping: "ping",
     preload: "preload",
     pattern: "pattern",
     playsInline: "playsinline",
     poster: "poster",

     rel: "rel",
     rev: "rev",
     readOnly: "readonly",
     required: "required",
     rows: "rows",
     referrerPolicy: "referrerpolicy",

     src: "src",
     span: "span",
     sandbox: "sandbox",
     srcDoc: "srcdoc",
     sizes: "sizes",
     srcSet: "srcset",
     srcLang: "srclang",
     step: "step",
     shape: "shape",
     start: "start",
     size: "size",
     rowSpan: "rowspan",
     scope: "scope",
     selected: "selected",
     spellCheck: "spellcheck",

     type: "type",
     title: "title",
     target: "target",

     useMap: "usemap",

     value: "value",

     wrap: "wrap",
     width: "width",
};
