import { CreateComponent } from "../../../index.js";

export default ({
    alt,
    crossOrigin,
    decoding,
    height,
    isMap,
    loading,
    referrerPolicy,
    sizes,
    src,
    srcSet,
    width,
    ueMap,
    props,
    key,
    events,
    hooks,
    style,
    flags,
}) => {
    return new CreateComponent({
        tag: "img",
        props: {
            ...props,
            alt,
            crossOrigin,
            decoding,
            height,
            isMap,
            loading,
            referrerPolicy,
            sizes,
            src,
            srcSet,
            width,
            ueMap,
        },
        key,
        events,
        hooks,
        style,
        flags,
    });
};
