import { CreateComponent } from "../../../index.js";

export default ({
    children,
    autoplay,
    controls,
    crossOrigin,
    height,
    loop,
    muted,
    playsInline,
    poster,
    preload,
    src,
    width,
    props,
    key,
    events,
    hooks,
    style,
    flags,
}) => {
    return new CreateComponent({
        children,
        tag: "video",
        props: {
            ...props,
            autoplay,
            controls,
            crossOrigin,
            height,
            loop,
            muted,
            playsInline,
            poster,
            preload,
            src,
            width,
        },
        key,
        events,
        hooks,
        style,
        flags,
    });
};
