export default {
     // HTML Attributes
     Attributes: {
          autoFocus: "autofocus",
          abbreviation: "abbr",
          align: "align",
          alt: "alt",
          allow: "allow",
          allowFullScreen: "allowfullscreen",
          allowPaymentRequest: "allowpaymentrequest",
          accept: "accept",
          autoComplete: "autocomplete",
          autoplay: "autoplay",
          acceptCharSet: "acceptcharset",
          action: "action",

          cols: "cols",
          color: "color",
          className: "className",
          controls: "controls",
          cite: "cite",
          crossOrigin: "crossorigin",
          coords: "coords",
          checked: "checked",
          charSet: "charset",
          colSpan: "colSpan",

          data: "data",
          dirName: "dirname",
          dir: "dir",
          disabled: "disabled",
          dateTime: "datetime",
          download: "download",
          decoding: "decoding",
          default: "default",

          encType: "enctype",

          form: "form",
          formAction: "formaction",
          formEncType: "formenctype",
          formMethod: "formmethod",
          formNoValidate: "formnovalidate",
          formTarget: "formtarget",
          isFor: "for",

          href: "href",
          hrefLang: "hreflang",
          height: "height",
          high: "high",
          headers: "headers",

          id: "id",
          isMap: "ismap",

          kind: "kind",

          loop: "loop",
          list: "list",
          loading: "loading",
          longDesc: "longdesc",
          low: "low",
          label: "label",

          max: "max",
          min: "min",
          media: "media",
          maxLength: "maxLength",
          minLength: "minLength",
          muted: "muted",
          multiple: "multiple",
          method: "method",

          name: "name",
          noValidate: "novalidate",
          noWrap: "nowrap",
          noShade: "noshade",

          open: "open",
          optimum: "optimum",

          placeholder: "placeholder",
          ping: "ping",
          preload: "preload",
          pattern: "pattern",
          playsInline: "playsinline",
          poster: "poster",

          rel: "rel",
          rev: "rev",
          readOnly: "readonly",
          required: "required",
          rows: "rows",
          referrerPolicy: "referrerpolicy",

          src: "src",
          span: "span",
          sandbox: "sandbox",
          srcDoc: "srcdoc",
          sizes: "sizes",
          srcSet: "srcset",
          srcLang: "srclang",
          step: "step",
          shape: "shape",
          start: "start",
          size: "size",
          rowSpan: "rowspan",
          scope: "scope",
          selected: "selected",
          spellCheck: "spellcheck",

          type: "type",
          title: "title",
          target: "target",

          useMap: "usemap",

          value: "value",

          wrap: "wrap",
          width: "width",
     },
     // CSS Attributes
     CssAttributes: {
          accentColor: "accent-color",
          alignContent: "align-content",
          alignItems: "align-items",
          alignSelf: "align-self",
          alignTracks: "align-tracks",
          all: "all",
          animation: "animation",
          animationDelay: "animation-delay",
          animationDuration: "animation-duration",
          animationFillMode: "animation-fill-mode",
          animationIterationCount: "animation-iteration-count",
          animationName: "animation-name",
          animationPlayState: "animation-play-state",
          animationTimingFunction: "animation-timing-function",
          appearance: "appearance",
          ascentOverride: "ascent-override",
          aspectRatio: "aspect-ratio",

          backdropFilter: "backdrop-filter",
          backfaceVisibility: "backface-visibility",
          background: "background",
          backgroundAttachment: "background-attachment",
          backgroundBlendMode: "background-blend-mode",
          backgroundClip: "background-clip",
          backgroundColor: "background-color",
          backgroundImage: "background-image",
          backgroundOrigin: "background-origin",
          backgroundPosition: "background-position",
          backgroundPositionX: "background-position-x",
          backgroundPositionY: "background-position-y",
          backgroundRepeat: "background-repeat",
          backgroundSize: "background-size",
          blockSize: "block-size",
          borderBlock: "border-block",
          borderBlockColor: "border-block-color",
          borderBlockStyle: "border-block-style",
          borderBlockWidth: "border-block-width",
          borderBlockEnd: "border-block-end",
          borderBlockEndColor: "border-block-end-color",
          borderBlockEndStyle: "border-block-end-style",
          borderBlockEndWidth: "border-block-end-width",
          borderBlockStart: "border-block-start",
          borderBlockStartColor: "border-block-start-color",
          borderBlockStartStyle: "border-block-start-style",
          borderBlockStartWidth: "border-block-start-width",
          border: "border",
          borderBottom: "border-bottom",
          borderBottomColor: "border-bottom-color",
          borderBottomLeftRadius: "border-bottom-left-radius",
          borderBottomRightRadius: "border-bottom-right-radius",
          borderBottomStyle: "border-bottom-style",
          borderBottomWidth: "border-bottom-width",
          borderCollapse: "border-collapse",
          borderColor: "border-color",
          borderEndEndRadius: "border-end-end-radius",
          borderEndStartRadius: "border-end-start-radius",
          borderStartEndRadius: "border-start-end-radius",
          borderStartStartRadius: "border-start-start-radius",
          borderImage: "border-image",
          borderImageOutset: "border-outset",
          borderImageRepeat: "border-image-repeat",
          borderImageSlice: "border-image-slice",
          borderImageSource: "border-image-source",
          borderImageWidth: "border-image-width",
          borderInline: "border-inline",
          borderInlineColor: "border-inline-color",
          borderInlineStyle: "border-inline-style",
          borderInlineWidth: "border-inline-width",
          borderInlineEnd: "border-inline-end",
          borderInlineEndColor: "border-inline-end-color",
          borderInlineEndStyle: "border-inline-end-style",
          borderInlineEndWidth: "border-inline-end-width",
          borderStartEnd: "border-start-end",
          borderInlineStartColor: "border-inline-start-color",
          borderInlineStartStyle: "border-inline-start-style",
          borderInlineStartWidth: "border-inline-start-width",
          borderLeft: "border-left",
          borderLeftColor: "border-left-color",
          borderLeftStyle: "border-left-style",
          borderLeftWidth: "border-left-width",
          borderRadius: "border-radius",
          borderRight: "border-right",
          borderRightColor: "border-right-color",
          borderRightStyle: "border-right-style",
          borderRightWidth: "border-right-width",
          borderSpacing: "border-spacing",
          borderStyle: "border-style",
          borderTop: "border-top",
          borderTopColor: "border-top-color",
          borderTopLeftRadius: "border-top-left-radius",
          borderTopRightRadius: "border-top-right-radius",
          borderTopStyle: "border-top-style",
          borderTopWidth: "border-top-width",
          borderWidth: "border-width",
          bottom: "bottom",
          boxDecorationBreak: "box-decoration-break",
          boxShadow: "box-shadow",
          boxSizing: "box-sizing",
          breakAfter: "break-after",
          breakBefore: "break-before",
          breakInside: "break-inside",

          captionSide: "caption-side",
          caretColor: "caret-color",
          clear: "clear",
          clip: "clip",
          clipPath: "clip-path",
          color: "color",
          colorAdjust: "color-adjust",
          colorScheme: "color-scheme",
          columnCount: "column-count",
          columnFill: "column-fill",
          columnGap: "column-gap",
          columnRule: "column-rule",
          columnRuleColor: "column-rule-color",
          columnRuleStyle: "column-rule-style",
          columnRuleWidth: "column-rule-width",
          columnSpan: "column-span",
          columnWidth: "column-width",
          columns: "columns",
          contain: "contain",
          content: "content",
          contentVisibility: "content-visibility",
          counterIncrement: "counter-increment",
          counterReset: "counter-reset",
          counterSet: "counter-set",
          cursor: "cursor",

          direction: "direction",
          display: "display",

          emptyCells: "empty-cells",

          filter: "filter",
          flex: "flex",
          flexBasis: "flex-basis",
          flexDirection: "flex-direction",
          flexFlow: "flex-flow",
          flexGrow: "flex-grow",
          flexShrink: "flex-shrink",
          flexWrap: "flex-wrap",
          float: "float",
          font: "font",
          fontFamily: "font-family",
          fontFeatureSettings: "font-feature-settings",
          fontKerning: "font-kerning",
          fontSize: "font-size",
          fontSizeAdjust: "font-size-adjust",
          fontStretch: "font-stretch",
          fontStyle: "font-style",
          fontSynthesis: "font-synthesis",
          fontVariant: "font-variant",
          fontVariantAlternates: "font-variant-alternates",
          fontVariantCaps: "font-variant-caps",
          fontVariantEastAsian: "font-variant-east-asian",
          fontVariantLigatures: "font-variant-ligatures",
          fontVariantNumeric: "font-variant-numeric",
          fontVariantPosition: "font-variant-position",
          fontVariantSettings: "font-variant-settings",
          fontWeight: "font-weight",
          forcedColorAdjust: "forced-color-adjust",

          gap: "gap",
          grid: "grid",
          gridArea: "grid-area",
          gridAutoColumns: "grid-auto-columns",
          gridAutoFlow: "grid-auto-flow",
          gridAutoRows: "grid-auto-rows",
          gridColumn: "grid-column",
          gridColumnEnd: "grid-column-end",
          gridColumnGap: "grid-column-gap",
          gridColumnStart: "grid-column-start",
          gridGap: "grid-gap",
          gridRow: "grid-row",
          gridRowEnd: "grid-row-end",
          gridRowGap: "grid-row-gap",
          gridRowStart: "grid-row-start",
          gridTemplate: "grid-template",
          gridTemplateAreas: "grid-template-areas",
          gridTemplateColumns: "grid-template-columns",
          gridTemplateRows: "grid-template-rows",

          hangingPunctuation: "hanging-punctuation",
          height: "height",
          hyphens: "hyphens",

          isolation: "isolation",
          imageOrientation: "image-orientation",
          imageRendering: "image-rendering",
          imageResolution: "image-resolution",
          initialLetter: "initial-letter",
          inlineSize: "inline-size",
          inset: "inset",
          insetBlock: "inset-block",
          insetBlockStart: "inset-block-end",
          insetBlockStart: "inset-block-start",
          insetBlock: "inset-inline",
          insetInlineStart: "inset-inline-end",
          insetInlineStart: "inset-inline-start",

          justifyContent: "justify-content",
          justifyItems: "justify-items",
          justifySelf: "justify-self",

          left: "left",
          letterSpacing: "letter-spacing",
          lineHeight: "line-height",
          lineBreak: "line-break",
          listStyle: "list-style",
          listStyleImage: "list-style-image",
          listStylePosition: "list-style-position",
          listStyleType: "list-style-type",

          margin: "margin",
          marginBlock: "margin-block",
          marginBlockEnd: "margin-block-end",
          marginBlockStart: "margin-block-start",
          marginBottom: "margin-bottom",
          marginInline: "margin-inline",
          marginInlineEnd: "margin-inline-end",
          marginInlineStart: "margin-inline-start",
          marginLeft: "margin-left",
          marginRight: "margin-right",
          marginTop: "margin-top",
          mask: "mask",
          maskBorder: "mask-border",
          maskBorderMode: "mask-border-mode",
          maskBorderOutset: "mast-border-outset",
          maskBorderRepeat: "mask-border-repeat",
          maskBorderSlice: "mask-border-slice",
          maskBorderSource: "mask-border-source",
          maskBorderWidth: "mask-border-width",
          maskClip: "mask-clip",
          maskComposite: "mask-composite",
          maskImage: "mask-image",
          maskMode: "mask-mode",
          maskOrigin: "mask-origin",
          maskPosition: "mask-position",
          maskRepeat: "mask-repeat",
          maskSize: "mask-size",
          maskType: "mask-type",
          mathStyle: "math-style",
          maxBlockSize: "max-block-size",
          maxInlineSize: "max-inline-size",
          minBlockSize: "min-block-size",
          minInlineSize: "min-inline-size",
          maxHeight: "max-height",
          maxWidth: "max-width",
          minHeight: "min-height",
          minWidth: "min-width",
          mixBlendMode: "mix-blend-mode",

          objectFit: "object-fit",
          objectPosition: "object-position",
          offset: "offset",
          offsetAnchor: "offset-anchor",
          offsetDistance: "offset-distance",
          offsetPath: "offset-path",
          offsetPosition: "offset-position",
          offsetRotate: "offset-rotate",
          opacity: "opacity",
          order: "order",
          orphans: "orphans",
          outline: "outline",
          outlineColor: "outline-color",
          outlineOffset: "outline-offset",
          outlineStyle: "outline-style",
          outlineWidth: "outline-width",
          overflow: "overflow",
          overflowAnchor: "overflow-anchor",
          overflowBlock: "overflow-block",
          overflowClipMargin: "overflow-clip-margin",
          overflowInline: "overflow-inline",
          overflowWrap: "overflow-wrap",
          overflowX: "overflow-x",
          overflowY: "overflow-y",
          overscrollBehavior: "overscroll-behavior",
          overscrollBehaviorBlock: "overscroll-behavior-block",
          overscrollBehaviorInline: "overscroll-behavior-inline",
          overscrollBehaviorX: "overscroll-behavior-x",
          overscrollBehaviorY: "overscroll-behavior-y",

          padding: "padding",
          paddingBlock: "padding-block",
          paddingBlockEnd: "padding-block-end",
          paddingBlockStart: "padding-block-start",
          paddingBottom: "padding-bottom",
          paddingInline: "padding-inline",
          paddingInlineEnd: "padding-inline-end",
          paddingInlineStart: "padding-inline-start",
          paddingLeft: "padding-left",
          paddingRight: "padding-right",
          paddingTop: "padding-top",
          pageBreakAfter: "page-break-after",
          pageBreakBefore: "page-break-before",
          pageBreakInside: "page-break-inside",
          perspective: "perspective",
          perspectiveOrigin: "perspective-origin",
          placeContent: "place-content",
          placeItems: "place-items",
          pointerEvents: "pointer-events",
          position: "position",

          quotes: "quotes",

          resize: "resize",
          revert: "revert",
          right: "right",
          rotate: "rotate",
          rowGap: "row-gap",
          rubyAlign: "ruby-align",
          rubyPosition: "ruby-position",

          scale: "scale",
          scrollBehavior: "scroll-behavior",
          scrollMargin: "scroll-margin",
          scrollMarginBlock: "scroll-margin-block",
          scrollMarginBlockEnd: "scroll-margin-block-end",
          scrollMarginBlockStart: "scroll-margin-block-start",
          scrollMarginBottom: "scroll-margin-bottom",
          scrollMarginInline: "scroll-margin-inline",
          scrollMarginInlineEnd: "scroll-margin-inline-end",
          scrollMarginInlineStart: "scroll-margin-inline-start",
          scrollMarginLeft: "scroll-margin-left",
          scrollMarginRight: "scroll-margin-right",
          scrollMarginTop: "scroll-margin-top",
          scrollPadding: "scroll-padding",
          scrollPaddingBlock: "scroll-padding-block",
          scrollPaddingBlockEnd: "scroll-padding-block-end",
          scrollPaddingBlockStart: "scroll-padding-block-start",
          scrollPaddingBottom: "scroll-padding-bottom",
          scrollPaddingInline: "scroll-padding-inline",
          scrollPaddingInline: "scroll-padding-inline-end",
          scrollPaddingInlineStart: "scroll-padding-inline-start",
          scrollPaddingLeft: "scroll-padding-left",
          scrollPaddingRight: "scroll-padding-right",
          scrollPaddingTop: "scroll-padding-top",
          scrollSnapAlign: "scroll-snap-align",
          scrollSnapStop: "scroll-snap-stop",
          scrollSnapType: "scroll-snap-type",
          scrollbarColor: "scrollbar-color",
          scrollbarGutter: "scrollbar-gutter",
          scrollbarWidth: "scrollbar-width",
          shapeImageThreshold: "shape-image-threshold",
          shapeMargin: "shape-margin",
          shapeOutside: "shape-outside",

          tabSize: "tab-size",
          tableLayout: "table-layout",
          textAlign: "text-align",
          textAlignLast: "text-align-last",
          textCombineUpright: "text-combine-upright",
          textDecoration: "text-decoration",
          textDecorationColor: "text-decoration-color",
          textDecorationLine: "text-decoration-line",
          textDecorationSkip: "text-decoration-skip",
          textDecorationSkipInk: "text-decoration-skip-ink",
          textDecorationStyle: "text-decoration-style",
          textDecorationThickness: "text-decoration-thickness",
          textEmphasis: "text-emphasis",
          textEmphasisColor: "text-emphasis-color",
          textEmphasisPosition: "text-emphasis-position",
          textEmphasisStyle: "text-emphasis-style",
          textIndent: "text-indent",
          textJustify: "text-justify",
          textOrientation: "text-orientation",
          textOverflow: "text-overflow",
          textRendering: "text-rendering",
          textShadow: "text-shadow",
          textSizeAdjust: "text-size-adjust",
          textTransform: "text-transform",
          textUnderlineOffset: "text-underline-offset",
          textUnderlinePosition: "text-underline-position",
          top: "top",
          touchAction: "touch-action",
          transform: "transform",
          transformBox: "transform-box",
          transformOrigin: "transform-origin",
          transformStyle: "transform-style",
          transition: "transition",
          transitionDelay: "transition-delay",
          transitionDuration: "transition-duration",
          transitionProperty: "transition-property",
          transitionTimingFunction: "transiton-timing-function",
          translate: "translate",

          unicodeBidi: "unicode-bidi",
          userSelect: "user-select",

          verticalAlign: "vertical-align",
          visibility: "visibility",

          whiteSpace: "white-space",
          width: "width",
          widows: "widows",
          wordBreak: "word-break",
          wordSpacing: "word-spacing",
          wordWrap: "word-wrap",
          writingMode: "writing-mode",

          zIndex: "z-index",

          // Webkit
          webkitLineClamp: "-webkit-line-clamp",
          webkitAppearance: "-webkit-appearance",
          webkitTextEmphasis: "-webkit-text-emphasis",

          // Moz
          mozAppearance: "-moz-appearance",
     },
     // Events
     Events: {
          onAbort: "abort",
          onAnimationEnd: "animationend",
          onAnimationIteration: "animationiteration",
          onAnimationStart: "animationstart",
          onAnimationEnd: "animationend",
          onBeforePrint: "beforeprint",
          onBeforeUnload: "beforeunload",
          onBlur: "blur",
          onCanPlay: "canplay",
          onCanPlayThrough: "canplaythrough",
          onChanged: "change",
          onClick: "click",
          onContextMenu: "contextmenu",
          onCopy: "copy",
          onCut: "cut",
          onDoubleClick: "dbclick",
          onDrag: "drag",
          onDragEnd: "dragend",
          onDragEnter: "dragenter",
          onDragLeave: "dragleave",
          onDragOver: "dragover",
          onDrop: "drop",
          onDurationChange: "durationchange",
          onEnded: "ended",
          onError: "error",
          onFocus: "focus",
          onFocusIn: "focusin",
          onFocusOut: "focusout",
          onFullScreenChange: "fullscreenchange",
          onHashChange: "hashchange",
          onChange: "input",
          onInvalid: "invalid",
          onKeydown: "keydown",
          onKeyPress: "keypress",
          onKeyUp: "keyup",
          onLoad: "load",
          onLoadedData: "loadeddata",
          onLoadedMetaData: "loadedmetadata",
          onLoadStart: "loadstart",
          onMessage: "message",
          onMouseDown: "mousedown",
          onMouseEnter: "mouseenter",
          onMouseLeave: "mouseleave",
          onMouseMove: "mousemove",
          onMouseOver: "mouseover",
          onMouseOut: "mouseout",
          onMouseUp: "mouseup",
          onOffline: "offline",
          onOnline: "online",
          onOpen: "open",
          onPageHide: "pagehide",
          onPageShow: "pageshow",
          onPaste: "paste",
          onPause: "pause",
          onPlay: "play",
          onPlaying: "playing",
          onPopState: "popstate",
          onProgress: "progress",
          onRateChange: "ratechange",
          onResize: "resize",
          onReset: "reset",
          onScroll: "scroll",
          onSearch: "search",
          onSeeked: "seeked",
          onSeeking: "seeking",
          onSelect: "select",
          onShow: "show",
          onStalled: "stalled",
          onStorage: "storage",
          onSubmit: "submit",
          onSuspend: "suspend",
          onTimeUpdate: "timeupdate",
          onToggle: "toggle",
          onTouchCancel: "touchcancel",
          onTouchEnd: "touchend",
          onTouchMove: "touchmove",
          onTouchStart: "touchStart",
          onTransitionEnd: "transitionend",
          onUnload: "unload",
          onVolumeChange: "volumnechange",
          onWaiting: "waiting",
          onWheel: "wheel",
     },
     // Create Component Flags
     Flags: {
          forceRerender: "force-rerender",
          renderIf: "render-if",
     },
     // Font face
     FontFace: {
          ascentOverride: "ascent-override",
          descentOverride: "descent-override",
          fontDisplay: "font-display",
          fontFamily: "font-family",
          fontStretch: "font-stretch",
          fontStyle: "font-style",
          fontWeight: "font-weight",
          fontVariant: "font-variant",
          fontFeatureSettings: "font-feature-settings",
          fontVariationSettings: "font-variation-settings",
          lineGapOverride: "line-gap-override",
          src: "src",
          unicodeRange: "unicode-range",
          sizeAdjust: "size-adjust",
     },
     // Create Component Hooks
     Hooks: {
          onCreated: "onCreated",
          onDestroyed: "onDestroyed",
          onUpdated: "onUpdated",
          beforeDestroyed: "beforeDestroyed",
     },
     // CSS Selectors
     CssSelectors: {
          normal: "",
          active: ":active",
          anyLink: ":any-link",
          checked: ":checked",
          default: ":default",
          defined: ":defined",
          disabled: ":disabled",
          empty: ":empty",
          enabled: ":enabled",
          first: ":first",
          firstChild: ":first-child",
          firstOfType: ":first-of-type",
          fullscreen: "fullscreen",
          focus: ":focus",
          focusVisible: ":focus-visible",
          focusWithin: ":focus-within",
          hover: ":hover",
          indeterminate: ":indeterminate",
          inRange: ":in-range",
          invalid: ":invalid",
          lastChild: ":last-child",
          lastOfType: ":last-of-type",
          link: ":link",
          onlyChild: ":only-child",
          onlyOfType: ":only-of-type",
          optional: ":optional",
          outOfRange: ":out-of-range",
          pictureInPicutre: ":picture-in-picture",
          placeholderShown: ":placeholder-shown",
          readOnly: ":read-only",
          readWrite: ":read-write",
          required: ":required",
          scope: ":scope",
          target: ":target",
          valid: ":valid",
          visited: ":visited",
          after: "::after",
          before: "::before",
          cue: "::cue",
          cueRegion: "::cue-region",
          firstLetter: "::first-letter",
          firstLine: "::first-line",
          fileSelectorButton: "::file-selector-button",
          placeholder: "::placeholder",
          selection: "::selection",
          marker: "::marker",
     },
     // Style Sheet keys
     StyleSheet: {
          normal: { name: "" },
          active: { name: ":active" },
          anyLink: { name: ":any-link" },
          checked: { name: ":checked" },
          default: { name: ":default" },
          defined: { name: ":defined" },
          disabled: { name: ":disabled" },
          empty: { name: ":empty" },
          enabled: { name: ":enabled" },
          first: { name: ":first" },
          firstChild: { name: ":first-child" },
          firstOfType: { name: ":first-of-type" },
          fullscreen: { name: "fullscreen" },
          focus: { name: ":focus" },
          focusVisible: { name: ":focus-visible" },
          focusWithin: { name: ":focus-within" },
          hover: { name: ":hover" },
          indeterminate: { name: ":indeterminate" },
          inRange: { name: ":in-range" },
          invalid: { name: ":invalid" },
          lastChild: { name: ":last-child" },
          lastOfType: { name: ":last-of-type" },
          link: { name: ":link" },
          onlyChild: { name: ":only-child" },
          onlyOfType: { name: ":only-of-type" },
          optional: { name: ":optional" },
          outOfRange: { name: ":out-of-range" },
          pictureInPicutre: { name: ":picture-in-picture" },
          placeholderShown: { name: ":placeholder-shown" },
          readOnly: { name: ":read-only" },
          readWrite: { name: ":read-write" },
          required: { name: ":required" },
          scope: { name: ":scope" },
          target: { name: ":target" },
          valid: { name: ":valid" },
          visited: { name: ":visited" },

          after: { name: "::after" },
          before: { name: "::before" },
          cue: { name: "::cue" },
          marker: { name: "::marker" },
          cueRegion: { name: "::cue-region" },
          firstLetter: { name: "::first-letter" },
          firstLine: { name: "::first-line" },
          fileSelectorButton: { name: "::file-selector-button" },
          placeholder: { name: "::placeholder" },
          selection: { name: "::selection" },

          animations: { type: "animation" },
          mediaQueries: { type: "media" },
     },
};
