export default {
     // HTML Attributes
     Attributes: {
          autoFocus: "autofocus",
          abbreviation: "abbr",
          align: "align",
          alt: "alt",
          allow: "allow",
          allowFullScreen: "allowfullscreen",
          allowPaymentRequest: "allowpaymentrequest",
          accept: "accept",
          autoComplete: "autocomplete",
          autoplay: "autoplay",
          acceptCharSet: "acceptcharset",
          action: "action",

          cols: "cols",
          color: "color",
          className: "className",
          controls: "controls",
          cite: "cite",
          crossOrigin: "crossorigin",
          coords: "coords",
          checked: "checked",
          charSet: "charset",
          colSpan: "colSpan",

          data: "data",
          dirName: "dirname",
          dir: "dir",
          disabled: "disabled",
          dateTime: "datetime",
          download: "download",
          decoding: "decoding",
          default: "default",
          draggable: "draggable",

          encType: "enctype",

          form: "form",
          formAction: "formaction",
          formEncType: "formenctype",
          formMethod: "formmethod",
          formNoValidate: "formnovalidate",
          formTarget: "formtarget",
          isFor: "for",

          href: "href",
          hrefLang: "hreflang",
          height: "height",
          high: "high",
          headers: "headers",

          id: "id",
          isMap: "ismap",

          kind: "kind",

          loop: "loop",
          list: "list",
          loading: "loading",
          longDesc: "longdesc",
          low: "low",
          label: "label",

          max: "max",
          min: "min",
          media: "media",
          maxLength: "maxLength",
          minLength: "minLength",
          muted: "muted",
          multiple: "multiple",
          method: "method",

          name: "name",
          noValidate: "novalidate",
          noWrap: "nowrap",
          noShade: "noshade",

          open: "open",
          optimum: "optimum",

          placeholder: "placeholder",
          ping: "ping",
          preload: "preload",
          pattern: "pattern",
          playsInline: "playsinline",
          poster: "poster",

          rel: "rel",
          rev: "rev",
          readOnly: "readonly",
          required: "required",
          rows: "rows",
          referrerPolicy: "referrerpolicy",

          src: "src",
          span: "span",
          sandbox: "sandbox",
          srcDoc: "srcdoc",
          sizes: "sizes",
          srcSet: "srcset",
          srcLang: "srclang",
          step: "step",
          shape: "shape",
          start: "start",
          size: "size",
          rowSpan: "rowspan",
          scope: "scope",
          selected: "selected",
          spellCheck: "spellcheck",

          type: "type",
          title: "title",
          target: "target",

          useMap: "usemap",

          value: "value",

          wrap: "wrap",
          width: "width",
     },
     // CSS Attributes
     CssAttributes: {
          accentColor: "accent-color",
          alignContent: "align-content",
          alignItems: "align-items",
          alignSelf: "align-self",
          alignTracks: "align-tracks",
          all: "all",
          animation: "animation",
          animationDelay: "animation-delay",
          animationDuration: "animation-duration",
          animationFillMode: "animation-fill-mode",
          animationIterationCount: "animation-iteration-count",
          animationName: "animation-name",
          animationPlayState: "animation-play-state",
          animationTimingFunction: "animation-timing-function",
          appearance: "appearance",
          ascentOverride: "ascent-override",
          aspectRatio: "aspect-ratio",

          backdropFilter: "backdrop-filter",
          backfaceVisibility: "backface-visibility",
          background: "background",
          backgroundAttachment: "background-attachment",
          backgroundBlendMode: "background-blend-mode",
          backgroundClip: "background-clip",
          backgroundColor: "background-color",
          backgroundImage: "background-image",
          backgroundOrigin: "background-origin",
          backgroundPosition: "background-position",
          backgroundPositionX: "background-position-x",
          backgroundPositionY: "background-position-y",
          backgroundRepeat: "background-repeat",
          backgroundSize: "background-size",
          blockSize: "block-size",
          borderBlock: "border-block",
          borderBlockColor: "border-block-color",
          borderBlockStyle: "border-block-style",
          borderBlockWidth: "border-block-width",
          borderBlockEnd: "border-block-end",
          borderBlockEndColor: "border-block-end-color",
          borderBlockEndStyle: "border-block-end-style",
          borderBlockEndWidth: "border-block-end-width",
          borderBlockStart: "border-block-start",
          borderBlockStartColor: "border-block-start-color",
          borderBlockStartStyle: "border-block-start-style",
          borderBlockStartWidth: "border-block-start-width",
          border: "border",
          borderBottom: "border-bottom",
          borderBottomColor: "border-bottom-color",
          borderBottomLeftRadius: "border-bottom-left-radius",
          borderBottomRightRadius: "border-bottom-right-radius",
          borderBottomStyle: "border-bottom-style",
          borderBottomWidth: "border-bottom-width",
          borderCollapse: "border-collapse",
          borderColor: "border-color",
          borderEndEndRadius: "border-end-end-radius",
          borderEndStartRadius: "border-end-start-radius",
          borderStartEndRadius: "border-start-end-radius",
          borderStartStartRadius: "border-start-start-radius",
          borderImage: "border-image",
          borderImageOutset: "border-outset",
          borderImageRepeat: "border-image-repeat",
          borderImageSlice: "border-image-slice",
          borderImageSource: "border-image-source",
          borderImageWidth: "border-image-width",
          borderInline: "border-inline",
          borderInlineColor: "border-inline-color",
          borderInlineStyle: "border-inline-style",
          borderInlineWidth: "border-inline-width",
          borderInlineEnd: "border-inline-end",
          borderInlineEndColor: "border-inline-end-color",
          borderInlineEndStyle: "border-inline-end-style",
          borderInlineEndWidth: "border-inline-end-width",
          borderStartEnd: "border-start-end",
          borderInlineStartColor: "border-inline-start-color",
          borderInlineStartStyle: "border-inline-start-style",
          borderInlineStartWidth: "border-inline-start-width",
          borderLeft: "border-left",
          borderLeftColor: "border-left-color",
          borderLeftStyle: "border-left-style",
          borderLeftWidth: "border-left-width",
          borderRadius: "border-radius",
          borderRight: "border-right",
          borderRightColor: "border-right-color",
          borderRightStyle: "border-right-style",
          borderRightWidth: "border-right-width",
          borderSpacing: "border-spacing",
          borderStyle: "border-style",
          borderTop: "border-top",
          borderTopColor: "border-top-color",
          borderTopLeftRadius: "border-top-left-radius",
          borderTopRightRadius: "border-top-right-radius",
          borderTopStyle: "border-top-style",
          borderTopWidth: "border-top-width",
          borderWidth: "border-width",
          bottom: "bottom",
          boxDecorationBreak: "box-decoration-break",
          boxShadow: "box-shadow",
          boxSizing: "box-sizing",
          breakAfter: "break-after",
          breakBefore: "break-before",
          breakInside: "break-inside",

          captionSide: "caption-side",
          caretColor: "caret-color",
          clear: "clear",
          clip: "clip",
          clipPath: "clip-path",
          color: "color",
          colorAdjust: "color-adjust",
          colorScheme: "color-scheme",
          columnCount: "column-count",
          columnFill: "column-fill",
          columnGap: "column-gap",
          columnRule: "column-rule",
          columnRuleColor: "column-rule-color",
          columnRuleStyle: "column-rule-style",
          columnRuleWidth: "column-rule-width",
          columnSpan: "column-span",
          columnWidth: "column-width",
          columns: "columns",
          contain: "contain",
          content: "content",
          contentVisibility: "content-visibility",
          counterIncrement: "counter-increment",
          counterReset: "counter-reset",
          counterSet: "counter-set",
          cursor: "cursor",

          direction: "direction",
          display: "display",

          emptyCells: "empty-cells",

          filter: "filter",
          flex: "flex",
          flexBasis: "flex-basis",
          flexDirection: "flex-direction",
          flexFlow: "flex-flow",
          flexGrow: "flex-grow",
          flexShrink: "flex-shrink",
          flexWrap: "flex-wrap",
          float: "float",
          font: "font",
          fontFamily: "font-family",
          fontFeatureSettings: "font-feature-settings",
          fontKerning: "font-kerning",
          fontSize: "font-size",
          fontSizeAdjust: "font-size-adjust",
          fontStretch: "font-stretch",
          fontStyle: "font-style",
          fontSynthesis: "font-synthesis",
          fontVariant: "font-variant",
          fontVariantAlternates: "font-variant-alternates",
          fontVariantCaps: "font-variant-caps",
          fontVariantEastAsian: "font-variant-east-asian",
          fontVariantLigatures: "font-variant-ligatures",
          fontVariantNumeric: "font-variant-numeric",
          fontVariantPosition: "font-variant-position",
          fontVariantSettings: "font-variant-settings",
          fontWeight: "font-weight",
          forcedColorAdjust: "forced-color-adjust",

          gap: "gap",
          grid: "grid",
          gridArea: "grid-area",
          gridAutoColumns: "grid-auto-columns",
          gridAutoFlow: "grid-auto-flow",
          gridAutoRows: "grid-auto-rows",
          gridColumn: "grid-column",
          gridColumnEnd: "grid-column-end",
          gridColumnGap: "grid-column-gap",
          gridColumnStart: "grid-column-start",
          gridGap: "grid-gap",
          gridRow: "grid-row",
          gridRowEnd: "grid-row-end",
          gridRowGap: "grid-row-gap",
          gridRowStart: "grid-row-start",
          gridTemplate: "grid-template",
          gridTemplateAreas: "grid-template-areas",
          gridTemplateColumns: "grid-template-columns",
          gridTemplateRows: "grid-template-rows",

          hangingPunctuation: "hanging-punctuation",
          height: "height",
          hyphens: "hyphens",

          isolation: "isolation",
          imageOrientation: "image-orientation",
          imageRendering: "image-rendering",
          imageResolution: "image-resolution",
          initialLetter: "initial-letter",
          inlineSize: "inline-size",
          inset: "inset",
          insetBlock: "inset-block",
          insetBlockStart: "inset-block-end",
          insetBlockStart: "inset-block-start",
          insetBlock: "inset-inline",
          insetInlineStart: "inset-inline-end",
          insetInlineStart: "inset-inline-start",

          justifyContent: "justify-content",
          justifyItems: "justify-items",
          justifySelf: "justify-self",

          left: "left",
          letterSpacing: "letter-spacing",
          lineHeight: "line-height",
          lineBreak: "line-break",
          listStyle: "list-style",
          listStyleImage: "list-style-image",
          listStylePosition: "list-style-position",
          listStyleType: "list-style-type",

          margin: "margin",
          marginBlock: "margin-block",
          marginBlockEnd: "margin-block-end",
          marginBlockStart: "margin-block-start",
          marginBottom: "margin-bottom",
          marginInline: "margin-inline",
          marginInlineEnd: "margin-inline-end",
          marginInlineStart: "margin-inline-start",
          marginLeft: "margin-left",
          marginRight: "margin-right",
          marginTop: "margin-top",
          mask: "mask",
          maskBorder: "mask-border",
          maskBorderMode: "mask-border-mode",
          maskBorderOutset: "mast-border-outset",
          maskBorderRepeat: "mask-border-repeat",
          maskBorderSlice: "mask-border-slice",
          maskBorderSource: "mask-border-source",
          maskBorderWidth: "mask-border-width",
          maskClip: "mask-clip",
          maskComposite: "mask-composite",
          maskImage: "mask-image",
          maskMode: "mask-mode",
          maskOrigin: "mask-origin",
          maskPosition: "mask-position",
          maskRepeat: "mask-repeat",
          maskSize: "mask-size",
          maskType: "mask-type",
          mathStyle: "math-style",
          maxBlockSize: "max-block-size",
          maxInlineSize: "max-inline-size",
          minBlockSize: "min-block-size",
          minInlineSize: "min-inline-size",
          maxHeight: "max-height",
          maxWidth: "max-width",
          minHeight: "min-height",
          minWidth: "min-width",
          mixBlendMode: "mix-blend-mode",

          objectFit: "object-fit",
          objectPosition: "object-position",
          offset: "offset",
          offsetAnchor: "offset-anchor",
          offsetDistance: "offset-distance",
          offsetPath: "offset-path",
          offsetPosition: "offset-position",
          offsetRotate: "offset-rotate",
          opacity: "opacity",
          order: "order",
          orphans: "orphans",
          outline: "outline",
          outlineColor: "outline-color",
          outlineOffset: "outline-offset",
          outlineStyle: "outline-style",
          outlineWidth: "outline-width",
          overflow: "overflow",
          overflowAnchor: "overflow-anchor",
          overflowBlock: "overflow-block",
          overflowClipMargin: "overflow-clip-margin",
          overflowInline: "overflow-inline",
          overflowWrap: "overflow-wrap",
          overflowX: "overflow-x",
          overflowY: "overflow-y",
          overscrollBehavior: "overscroll-behavior",
          overscrollBehaviorBlock: "overscroll-behavior-block",
          overscrollBehaviorInline: "overscroll-behavior-inline",
          overscrollBehaviorX: "overscroll-behavior-x",
          overscrollBehaviorY: "overscroll-behavior-y",

          padding: "padding",
          paddingBlock: "padding-block",
          paddingBlockEnd: "padding-block-end",
          paddingBlockStart: "padding-block-start",
          paddingBottom: "padding-bottom",
          paddingInline: "padding-inline",
          paddingInlineEnd: "padding-inline-end",
          paddingInlineStart: "padding-inline-start",
          paddingLeft: "padding-left",
          paddingRight: "padding-right",
          paddingTop: "padding-top",
          pageBreakAfter: "page-break-after",
          pageBreakBefore: "page-break-before",
          pageBreakInside: "page-break-inside",
          perspective: "perspective",
          perspectiveOrigin: "perspective-origin",
          placeContent: "place-content",
          placeItems: "place-items",
          pointerEvents: "pointer-events",
          position: "position",

          quotes: "quotes",

          resize: "resize",
          revert: "revert",
          right: "right",
          rotate: "rotate",
          rowGap: "row-gap",
          rubyAlign: "ruby-align",
          rubyPosition: "ruby-position",

          scale: "scale",
          scrollBehavior: "scroll-behavior",
          scrollMargin: "scroll-margin",
          scrollMarginBlock: "scroll-margin-block",
          scrollMarginBlockEnd: "scroll-margin-block-end",
          scrollMarginBlockStart: "scroll-margin-block-start",
          scrollMarginBottom: "scroll-margin-bottom",
          scrollMarginInline: "scroll-margin-inline",
          scrollMarginInlineEnd: "scroll-margin-inline-end",
          scrollMarginInlineStart: "scroll-margin-inline-start",
          scrollMarginLeft: "scroll-margin-left",
          scrollMarginRight: "scroll-margin-right",
          scrollMarginTop: "scroll-margin-top",
          scrollPadding: "scroll-padding",
          scrollPaddingBlock: "scroll-padding-block",
          scrollPaddingBlockEnd: "scroll-padding-block-end",
          scrollPaddingBlockStart: "scroll-padding-block-start",
          scrollPaddingBottom: "scroll-padding-bottom",
          scrollPaddingInline: "scroll-padding-inline",
          scrollPaddingInline: "scroll-padding-inline-end",
          scrollPaddingInlineStart: "scroll-padding-inline-start",
          scrollPaddingLeft: "scroll-padding-left",
          scrollPaddingRight: "scroll-padding-right",
          scrollPaddingTop: "scroll-padding-top",
          scrollSnapAlign: "scroll-snap-align",
          scrollSnapStop: "scroll-snap-stop",
          scrollSnapType: "scroll-snap-type",
          scrollbarColor: "scrollbar-color",
          scrollbarGutter: "scrollbar-gutter",
          scrollbarWidth: "scrollbar-width",
          shapeImageThreshold: "shape-image-threshold",
          shapeMargin: "shape-margin",
          shapeOutside: "shape-outside",

          tabSize: "tab-size",
          tableLayout: "table-layout",
          textAlign: "text-align",
          textAlignLast: "text-align-last",
          textCombineUpright: "text-combine-upright",
          textDecoration: "text-decoration",
          textDecorationColor: "text-decoration-color",
          textDecorationLine: "text-decoration-line",
          textDecorationSkip: "text-decoration-skip",
          textDecorationSkipInk: "text-decoration-skip-ink",
          textDecorationStyle: "text-decoration-style",
          textDecorationThickness: "text-decoration-thickness",
          textEmphasis: "text-emphasis",
          textEmphasisColor: "text-emphasis-color",
          textEmphasisPosition: "text-emphasis-position",
          textEmphasisStyle: "text-emphasis-style",
          textIndent: "text-indent",
          textJustify: "text-justify",
          textOrientation: "text-orientation",
          textOverflow: "text-overflow",
          textRendering: "text-rendering",
          textShadow: "text-shadow",
          textSizeAdjust: "text-size-adjust",
          textTransform: "text-transform",
          textUnderlineOffset: "text-underline-offset",
          textUnderlinePosition: "text-underline-position",
          top: "top",
          touchAction: "touch-action",
          transform: "transform",
          transformBox: "transform-box",
          transformOrigin: "transform-origin",
          transformStyle: "transform-style",
          transition: "transition",
          transitionDelay: "transition-delay",
          transitionDuration: "transition-duration",
          transitionProperty: "transition-property",
          transitionTimingFunction: "transiton-timing-function",
          translate: "translate",

          unicodeBidi: "unicode-bidi",
          userSelect: "user-select",

          verticalAlign: "vertical-align",
          visibility: "visibility",

          whiteSpace: "white-space",
          width: "width",
          widows: "widows",
          wordBreak: "word-break",
          wordSpacing: "word-spacing",
          wordWrap: "word-wrap",
          writingMode: "writing-mode",

          zIndex: "z-index",

          // Webkit
          webkitLineClamp: "-webkit-line-clamp",
          webkitAppearance: "-webkit-appearance",
          webkitTextEmphasis: "-webkit-text-emphasis",
          webkitHyphens: "-webkit-hyphens",

          // Moz
          mozAppearance: "-moz-appearance",
          mozTabSize: "-moz-tab-size",
          mozHyphens: "-moz-hyphens",

          // O
          oTabSize: "-o-tab-size",

          // MS
          msHyphens: "-ms-hyphens",
     },
     // Events
     Events: {
          onAbort: { listener: "abort", on: "onabort" },
          onAnimationEnd: { listener: "animationend", on: "onanimationend" },
          onAnimationIteration: { listener: "animationiteration", on: "onanimationiteration" },
          onAnimationStart: { listener: "animationstart", on: "onanimationstart" },
          onAnimationEnd: { listener: "animationend", on: "onanimationend" },
          onBeforePrint: { listener: "beforeprint", on: "onbeforeprint" },
          onBeforeUnload: { listener: "beforeunload", on: "onberforeunload" },
          onBlur: { listener: "blur", on: "onblur" },
          onCanPlay: { listener: "canplay", on: "oncanplay" },
          onCanPlayThrough: { listener: "canplaythrough", on: "oncanplaythroug" },
          onChanged: { listener: "change", on: "onchange" },
          onClick: { listener: "click", on: "onclick" },
          onContextMenu: { listener: "contextmenu", on: "oncontextmenu" },
          onCopy: { listener: "copy", on: "oncopy" },
          onCut: { listener: "cut", on: "oncut" },
          onDoubleClick: { listener: "dblclick", on: "ondblclick" },
          onDrag: { listener: "drag", on: "ondrag" },
          onDragEnd: { listener: "dragend", on: "ondragend" },
          onDragEnter: { listener: "dragenter", on: "ondragenter" },
          onDragLeave: { listener: "dragleave", on: "ondragleave" },
          onDragOver: { listener: "dragover", on: "ondragover" },
          onDrop: { listener: "drop", on: "ondrop" },
          onDurationChange: { listener: "durationchange", on: "ondurationchange" },
          onEnded: { listener: "ended", on: "onended" },
          onError: { listener: "error", on: "onerror" },
          onFocus: { listener: "focus", on: "onfocus" },
          onFocusIn: { listener: "focusin", on: "onfocusin" },
          onFocusOut: { listener: "focusout", on: "onfocusout" },
          onFullScreenChange: { listener: "fullscreenchange", on: "onfullscreenchange" },
          onHashChange: { listener: "hashchange", on: "onhashchange" },
          onChange: { listener: "input", on: "oninput" },
          onInvalid: { listener: "invalid", on: "oninvalid" },
          onKeyDown: { listener: "keydown", on: "onkeydown" },
          onKeyPress: { listener: "keypress", on: "onkeypress" },
          onKeyUp: { listener: "keyup", on: "onkeyup" },
          onLoad: { listener: "load", on: "onload" },
          onLoadedData: { listener: "loadeddata", on: "onloadeddata" },
          onLoadedMetaData: { listener: "loadedmetadata", on: "onloadedmetadata" },
          onLoadStart: { listener: "loadstart", on: "onloadstart" },
          onMessage: { listener: "message", on: "onmessage" },
          onMouseDown: { listener: "mousedown", on: "onmousedown" },
          onMouseEnter: { listener: "mouseenter", on: "onmouseenter" },
          onMouseLeave: { listener: "mouseleave", on: "onmouseleave" },
          onMouseMove: { listener: "mousemove", on: "onmousemove" },
          onMouseOver: { listener: "mouseover", on: "onmouseover" },
          onMouseOut: { listener: "mouseout", on: "onmouseout" },
          onMouseUp: { listener: "mouseup", on: "onmouseup" },
          onOffline: { listener: "offline", on: "ononffline" },
          onOnline: { listener: "online", on: "ononline" },
          onOpen: { listener: "open", on: "onopen" },
          onPageHide: { listener: "pagehide", on: "onpagehide" },
          onPageShow: { listener: "pageshow", on: "onpageshow" },
          onPaste: { listener: "paste", on: "onpaste" },
          onPause: { listener: "pause", on: "onpause" },
          onPlay: { listener: "play", on: "onplay" },
          onPlaying: { listener: "playing", on: "onplaying" },
          onPopState: { listener: "popstate", on: "onpopstate" },
          onProgress: { listener: "progress", on: "onprogress" },
          onRateChange: { listener: "ratechange", on: "onratechange" },
          onResize: { listener: "resize", on: "onresize" },
          onReset: { listener: "reset", on: "onreset" },
          onScroll: { listener: "scroll", on: "onscroll" },
          onSearch: { listener: "search", on: "onsearch" },
          onSeeked: { listener: "seeked", on: "onseeked" },
          onSeeking: { listener: "seeking", on: "onseeking" },
          onSelect: { listener: "select", on: "onselect" },
          onSelectionChange: { listener: "selectionchange", on: "onselectionchange" },
          onShow: { listener: "show", on: "onshow" },
          onStalled: { listener: "stalled", on: "onstalled" },
          onStorage: { listener: "storage", on: "onstorage" },
          onSubmit: { listener: "submit", on: "onsubmit" },
          onSuspend: { listener: "suspend", on: "onsuspend" },
          onTimeUpdate: { listener: "timeupdate", on: "ontimeupdate" },
          onToggle: { listener: "toggle", on: "ontoggle" },
          onTouchCancel: { listener: "touchcancel", on: "ontouchcancel" },
          onTouchEnd: { listener: "touchend", on: "ontouchend" },
          onTouchMove: { listener: "touchmove", on: "ontouchmove" },
          onTouchStart: { listener: "touchstart", on: "ontouchstart" },
          onTransitionEnd: { listener: "transitionend", on: "ontransitionend" },
          onUnload: { listener: "unload", on: "onunload" },
          onVolumeChange: { listener: "volumnechange", on: "onvolumechange" },
          onWaiting: { listener: "waiting", on: "onwaiting" },
          onWheel: { listener: "wheel", on: "onwheel" },
     },
     // Create Component Flags
     Flags: {
          forceRerender: "force-rerender",
          renderIf: "render-if",
     },
     // Font face
     FontFace: {
          ascentOverride: "ascent-override",
          descentOverride: "descent-override",
          fontDisplay: "font-display",
          fontFamily: "font-family",
          fontStretch: "font-stretch",
          fontStyle: "font-style",
          fontWeight: "font-weight",
          fontVariant: "font-variant",
          fontFeatureSettings: "font-feature-settings",
          fontVariationSettings: "font-variation-settings",
          lineGapOverride: "line-gap-override",
          src: "src",
          unicodeRange: "unicode-range",
          sizeAdjust: "size-adjust",
     },
     // Create Component Hooks
     Hooks: {
          onCreated: "onCreated",
          onDestroyed: "onDestroyed",
          onUpdated: "onUpdated",
          beforeDestroyed: "beforeDestroyed",
          onRef: "onRef",
     },
     // CSS Selectors
     CssSelectors: {
          normal: "",
          active: ":active",
          anyLink: ":any-link",
          checked: ":checked",
          default: ":default",
          defined: ":defined",
          disabled: ":disabled",
          empty: ":empty",
          enabled: ":enabled",
          first: ":first",
          firstChild: ":first-child",
          firstOfType: ":first-of-type",
          fullscreen: "fullscreen",
          focus: ":focus",
          focusVisible: ":focus-visible",
          focusWithin: ":focus-within",
          hover: ":hover",
          indeterminate: ":indeterminate",
          inRange: ":in-range",
          invalid: ":invalid",
          lastChild: ":last-child",
          lastOfType: ":last-of-type",
          link: ":link",
          onlyChild: ":only-child",
          onlyOfType: ":only-of-type",
          optional: ":optional",
          outOfRange: ":out-of-range",
          pictureInPicutre: ":picture-in-picture",
          placeholderShown: ":placeholder-shown",
          readOnly: ":read-only",
          readWrite: ":read-write",
          required: ":required",
          scope: ":scope",
          target: ":target",
          valid: ":valid",
          visited: ":visited",
          after: "::after",
          before: "::before",
          cue: "::cue",
          cueRegion: "::cue-region",
          firstLetter: "::first-letter",
          firstLine: "::first-line",
          fileSelectorButton: "::file-selector-button",
          placeholder: "::placeholder",
          selection: "::selection",
          marker: "::marker",

          // webkit

          webkitScrollbar: "::-webkit-scrollbar",
          webkitScrollbarTrack: "::-webkit-scrollbar-track",
          webkitScrollbarThumb: "::-webkit-scrollbar-thumb",
          webkitScrollbarThumbHover: "::-webkit-scrollbar-thumb:hover",
          webkitScrollbarThumbActive: "::-webkit-scrollbar-thumb:active",
     },
};
